### ISSUE TITLE
Add `cancel` button when editing a bill

### ISSUE THREAD

**Issue by MagicMilly** [spiral-project/ihatemoney#1001]
When choosing to edit an existing bill, the only way to cancel the action is to go back in your browser, or to select `submit` without adding any changes. 

<img width="665" alt="ihatemoney-edit-bill-issue" src="https://user-images.githubusercontent.com/34486154/157727197-011c6f66-1b45-4afb-9410-171c9b6ac4bf.png">

**Comment by almet** [comment]
Thanks, are you willing to propose such change?

**Comment by erwan-lacoudre** [comment]
Hi, I’m new to open source and I would like to try to implement the change if it’s still available

**Comment by almet** [comment]
Yes ! Don't hesitate to follow thé docs about this, your help is welcome 👍

**Comment by almet** [comment]
@MagicMilly how are you doing with this? Do you need any help?

**Comment by erwan-lacoudre** [comment]
Sorry for the delay. I'm still working on this issue but I have a hard time implementing it. I think I see what needs to be modified, but I can't quite see how to bypass the required field when creating a BillForm. That's what make me think maybe I'm not doing it properly.

For now I have added a "Cancel" SubmitField in the BillForm class. But I still need to have all the required fields given even if I want to cancel the modification. I never used WTForm so I'm probably missing something.

**Comment by almet** [comment]
You probably can implement this by adding a link (themed as a button)
