### ISSUE TITLE
Hide "each" amount when there's only one recipient

### ISSUE THREAD

**Issue by georgefst** [spiral-project/ihatemoney#1002]
When there's only one person in the `For whom?` column (this is the case for the slight majority of my transactions), the `How much?` column is unnecessarily cluttered, with the same value always appearing twice. I think it would read a lot more nicely if instead of e.g. `12.95 (12.95 each)`, we just saw `12.95`.

I was going to try to open a PR for this, assuming it would be pretty simple, but it relies on some sort of template/macro system rather than a proper programming language, and I just don't have the time to look in to it.

**Comment by almet** [comment]
That would be great !

**Comment by zorun** [comment]
Note that when there are weights on participants, even if there's a single recipient, the values will not be the same. It could be `12.98 (6.49 each)` with a weight of 2.

**Comment by georgefst** [comment]
> Note that when there are weights on participants, even if there's a single recipient, the values will not be the same. It could be `12.98 (6.49 each)` with a weight of 2.

Okay, I've never used that option. I guess we can just make an exception in that case, Or just test whether the total and the "each" amount are equal, rather than looking directly at the number of participants.

**Comment by johnl2102** [comment]
Hi, myself and another contributor are interested in working on this issue. What would be the best way to get started?
