### ISSUE TITLE
PostgreSQL/MySQL driver dependencies in Docker image

### ISSUE THREAD

**Issue by marcogiorgio** [spiral-project/ihatemoney#1003]
Hi,
I configured the Docker image to use a PostgreSQL database but I found out that the necessary driver (psycopg2-binary) was not included in the base image and I had to extend it to include this dependency.
Would it be possible to add these directly in the base image?
Thanks

**Comment by almet** [comment]
cc @youegraillot, what do you think?

**Comment by zorun** [comment]
This is already done (see #927 and #919), we just need to do a stable release with these changes...

#964

**Comment by marcogiorgio** [comment]
> This is already done (see #927 and #919), we just need to do a stable release with these changes...
> 
> #964

My bad, I only searched in open issues before opening this one

**Comment by zorun** [comment]
No problem, the mistake is not yours, this release is long overdue!
