### ISSUE TITLE
Can't click on anything when green notification pops up

### ISSUE THREAD

**Issue by llego** [spiral-project/ihatemoney#1017]
A green notification pops up when a new bill has been added or a user has been added. After the green notication has popped up, it has to be closed before you can use the mouse again. You can't click on anything before closing the notification.

It would be nice to be able to use the mouse even though I don't close the notification.

![image](https://user-images.githubusercontent.com/8949656/164713255-9acaa4d5-a10a-4b9b-a087-f9233146f7f4.png)

**Comment by almet** [comment]
Thanks for taking the time to report this, it had been solved in #903.
