### ISSUE TITLE
Depreciated Code Dependency in Merge Checks

### ISSUE THREAD

**Issue by a-angeles13** [spiral-project/ihatemoney#1018]
Noted in my comment in pull request #1016.

The check tests (3.7, minimal, postgresql; 3.7, minimal, mariadb; 3.9, minimal, sqlite; 3.10, minimal, sqlite) are failing due to [depreciation in Werkzeug 2.1](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#:~:text=werkzeug.locals%20and,deprecated%20code.%20%232276)

Specifically, self.local.__ident_func__ in line 215 of <test_path>/werkzeug/local.py is now depreciated and will not work in Python versions 3.7+. This was noted in a warning on line 34 of test of 3.7, minimal, postgresql in a previously successful merge. [link](https://github.com/spiral-project/ihatemoney/runs/5528226214?check_suite_focus=true#:~:text=../home/runner/work,self._local.__ident_func__).

I suggest that the merge check test suite be prioritized because any future pull requests will be blocked under any Werkzeug 2.1+.

**Comment by almet** [comment]
Hey, thanks for your input ! We've discussed this in #1015 and I think it should be solved when we merge it :-)
