### ISSUE TITLE
Flash message overlays the "Add participant" input field

### ISSUE THREAD

**Issue by koekie** [spiral-project/ihatemoney#1035]
It is not possible to bring the focus to the "Add participant" input field or click the "Add" button using the mouse pointer on the hosted version on https://ihatemoney.org/
The flash message container seems to sit on top the input and button. (see the attached image below).

Maybe a side effect of the fixes for #903 and/or #943?

I am using `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0 `
and also tested it on `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36`

Hope this helps making your very useful app even better ;)

![image](https://user-images.githubusercontent.com/643692/177140236-81abca6a-5274-49ff-9c34-6dbcb38324ff.png)

**Comment by Glandos** [comment]
This has been fixed with #943 and published in 5.2.0.
It seems however that ihatemoney.org is not up to date. @almet can you check this? Or is it for someone else?

**Comment by almet** [comment]
Cc @Natim

**Comment by almet** [comment]
Hey, I've updated the hosted version to the latest release (5.2.0). This should be fixed. Thanks for letting us know!
