### ISSUE TITLE
Menu icon is not visible on mobile

### ISSUE THREAD

**Issue by xouillet** [spiral-project/ihatemoney#1055]
Hi everyone,

On mobile display, the menu icon (hamburger) is not visible. This can be reproduced on firefox and chromium with responsive debug tools.

![20220815_18h33m12s_grim](https://user-images.githubusercontent.com/310587/184676397-9d85dec4-2cac-4bda-ae64-2f2dc75ec6dd.png)

**Comment by Glandos** [comment]
Hi @xouillet and thanks for the report. I fixed this, but it won't be available soon on the main instance.

I see that holidays is the right time to use a smartphone for IHateMoney :wink:
