### ISSUE TITLE
Creating new project on hosted site fails on captcha

### ISSUE THREAD

**Issue by kannes** [spiral-project/ihatemoney#1060]
Sorry in advance if this bug tracker is not meant for issues with the hosted site.

I tried to create a new project but the captcha validation always fails. I am 99.9% sure I am human and answering it correctly:

![Bildschirmfoto_2022-09-09_09-19-07](https://user-images.githubusercontent.com/7661092/189294623-be979967-42bc-437e-894c-49623e6ca4fb.png)

I tried in multiple browsers but always got the verification fail.

**Comment by Glandos** [comment]
Hi, thanks for the report.
It seems that it doesn't work in German. But in English it works fine. I have to find the real reason, but as a workaround, you can switch to English for the project creation, and then switch back to your beloved language.

**Comment by kannes** [comment]
Perfekt, vielen Dank! ;)

Works like a charm then.

**Comment by zorun** [comment]
@Glandos good catch :)

We should probably also test the answer against plain "euro" (case-insensitive) instead of only checking against a translation...

**Comment by Glandos** [comment]
In fact, it really depends on localisation data. For example, in Hebrew, [it is far from being "euro"](https://github.com/spiral-project/ihatemoney/blob/39bf774941fb7553cd8b14f4483751fad6f84fdb/ihatemoney/translations/he/LC_MESSAGES/messages.po#L74). Same for Greek, Chinese, and every non-latin language.

Even a "simple" word CAPTCHA is hard ;)
