### ISSUE TITLE
Dropping Python 3.6 support

### ISSUE THREAD

**Issue by Glandos** [spiral-project/ihatemoney#1063]
So, it seems that every library developer is dropping support for Python 3.6:
- Flask
- Werkzeug
- Flask-limiter

The latter is the most important to me, because it allows to close some security issues regarding spamming.

On the other hand, some Linux distribution still use Python 3.6 as the main supported (?) version. Mainly Centos 7 and OpenSUSE Leap. Centos is [going away in 2024](https://endoflife.date/centos), and OpenSUSE Leap 15.4 will [fade in late 2023](https://endoflife.date/opensuse)

I don't think it's a good idea to support Python3.6 until then, but… we have a difficult choice:
- Keep Python 3.6 and give the most of security update for IHM users. Flask-limiter is not an option though, since recent version ([that are needed for what we do](https://github.com/alisaifee/flask-limiter/issues/350)) don't support it
- Move to (at least) Python 3.7, and drop support for some users that don't want to (or can't) upgrade their Python.

I really don't know the Python landscape in our users, so it's a difficult choice. For example, what is the state of the main instance in ihatemoney.org?

**Comment by almet** [comment]
Thanks for bringing this up. I believe if this is blocking development, dropping support for older python version is a good idea. There are ways to install newer versions of python on these systems anyway.

About the hosted instance, it's able to run recent versions of python, so we don't have to worry.

Of course, if anybody here depends on older systems which aren't updated wrt python, let us know!

**Comment by almet** [comment]
Closing, we don't support python 3.6 anymore.
