### ISSUE TITLE
Make data immutable

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#1071]
It could be useful to mark data as immutable, or to attribute it to someone, so data doesn't get accidentally or intentionally removed. (Thanks to Michiel Leenaars for the suggestion)

**Comment by symphorien** [comment]
an interesting variant would be to prevent edits on transactions which are more than >1 day old. This leaves some time to edit typos etc but not to rewrite old history

**Comment by almet** [comment]
That seems interesting. If we go this way, we could enable/disable it project-wide.

The main problem I see with the author attribution is that users aren't currently identified on their own (everybody connects with the same project-credentials), so changing this would mean a rework of the authentication workflow. Not sure we want this, because it adds complexity.

**Comment by symphorien** [comment]
One account per user is not necessarily required, we can let anyone edit any less-than-a-day-old transaction.

**Comment by Glandos** [comment]
Since there is now sqlalchemy-continuum, nearly all bits of a project can be reverted quite easily. The most tedious part is the UI/UX design.

Some UX rules I quickly studied for my work insist on this do-not-forbid-deletion step, but implement a quick and easy undo. And make deletion a bit harder for unforgivable actions (like the current project deletion workflow).

It's easy to say, but not easy to implement though…

**Comment by chmac** [comment]
I'd be opposed to this feature without an option to disable it, and I'll explain what happened in our budge to explain why.

We're sharing a house for a month and sharing costs. We had a friend visit for a couple of days. He was added to the budget and to a couple of receipts, but we never got any money from him. By now he's long gone and we decided he paid for some stuff which wasn't in the budget, so we said we'd just remove him from the budget. I was able to deactivate him, but the his share was still included. So I had to edit two bills to remove him from a share.

If the data became immutable after 24h then later removing a user would be a lot more difficult.

**Comment by georgefst** [comment]
Personally, I'd hate to lose the ability to correct old mistakes. And I'd be unlikely to ever enable such a setting project-wide.

What I'd really want is an edit log. So in the (in my use cases so far, unlikely) event that I'd suspect tampering, I could go and browse the history.

**Comment by almet** [comment]
Thanks :-) FWIW, we already have an edit log :-)

**Comment by georgefst** [comment]
There's an edit log? How does one access it?

**Comment by almet** [comment]
It's named history, check on one of your projects 😊

Le 12 novembre 2022 01:46:26 GMT+01:00, George Thomas ***@***.***> a écrit :

**Comment by georgefst** [comment]
Aha, finally found it, thanks.

(although it isn't actually working for me: https://github.com/spiral-project/ihatemoney/issues/1038#issuecomment-1312503403)

**Comment by almet** [comment]
Okay closing this for now then.
