### ISSUE TITLE
Choose some languages and discard others

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#1076]
I feel that we support too many languages, with a lot of them not being translated more that 10% of the strings. Should we drop some languages? What do you think?

**Comment by Glandos** [comment]
I think it's not an issue to have many unfinished translation **in the repository**.
We should only show them in the menu if their quality reaches a certain goal, which is the case right now: https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/default_settings.py#L13

So for me, I don't think it's an issue. Plus, if someone see a language that's already started, it's sometimes a motivation to finish it.

**Comment by almet** [comment]
Okay, thanks. Let's keep it that way then :-)
