### ISSUE TITLE
Joining a room using URL makes other rooms menu polluted

### ISSUE THREAD

**Issue by emateizet** [spiral-project/ihatemoney#1081]
Reproduction steps - use private browsing to start with a clean setup:
1. Go to [ihatemoney.org](https://ihatemoney.org/demo/) demo instance
2. Open drop-down menu - there are no other rooms listed
![Screenshot from 2022-10-22 18-25-56](https://user-images.githubusercontent.com/112796728/197351032-cd5dc77b-2186-4c4a-bce8-b3022c6bf367.png)
3. Go to https://ihatemoney.org/raisingsomebugs123456/join/WyJyYWlzaW5nc29tZWJ1Z3MxMjM0NTYiXQ.bdc5s4d6rqx9qLjem3tKrGi-UyA twice in a new tab
4. Switch back to the tab with demo instance and refresh
5. Open drop-down menu - test room is listed **twice**
![Screenshot from 2022-10-22 18-26-56](https://user-images.githubusercontent.com/112796728/197351554-c7c351d4-71d0-4c25-8203-d5baace3bb9b.png)

Expected:
Test room is listed **once**

**Comment by Glandos** [comment]
With a perfect bug report comes a quick fix. Thanks a lot!
