### ISSUE TITLE
Balance changes when changing pages

### ISSUE THREAD

**Issue by DanielNetoP** [spiral-project/ihatemoney#1090]
When moving from page 1 (default) to page 2, the balance values on the left column with the names of the users changes based on the page itself.

For example:
| Users  | Page 1 Balance | Page 2 Balance |
|--------|----------------|----------------|
| User 1 | -23            | +65            |
| User2  | +23            | +52            |

The balance should not change when changing pages, we should use the total, and not the total of the rows for that specific page

**Comment by almet** [comment]
Yes, that seems to be a bug!

**Comment by vrrock** [comment]
My team would like to work on this issue. We are from CMU and as part of an open-source project, would like to solve this.

**Comment by almet** [comment]
@kellikuramoto Did you manage to reproduce?

**Comment by vrrock** [comment]
Hi @almet, we were unable to reproduce this issue!

**Comment by chestnutFan** [comment]
Hey guys, just trying to help out. 

Tried to reproduce the bug but failed too. The balance table works well. Then I looked into the code and found the balance value calculated based on the whole project, not bills on a specific page. It should not be affected by page-changing.

I doubt this bug was triggered by other operations. Would @DanielNetoP mind offering more details?

**Comment by GingLuo** [comment]
I'm using chrome on mac, when I add lots of bills, they just stay on the same page that's getting longer and longer. Is this an issue specific to some browsers?

**Comment by chestnutFan** [comment]
> I'm using chrome on mac, when I add lots of bills, they just stay on the same page that's getting longer and longer. Is this an issue specific to some browsers?

Look into the code and you would find the initial setting is 100 bills per page. I'm afraid you have to add so many to have the second page. However, you can change the setting yourself for convenience (like 2 bills per page)

**Comment by zorun** [comment]
I can't reproduce this bug either. Pagination should definitely not affect balance computations.

@DanielNetoP  which exact version of Ihatemoney exhibits this bug?

**Comment by DanielNetoP** [comment]
I'm using the version 5.2.0 on docker with a mariadb database

I'm going to try on the next couple of days to export everything (json/csv) and import on a fresh install, maybe there's something wrong with my setup, I'll report my results in a couple of days

**Comment by DanielNetoP** [comment]
I exported a json of all the items and imported on a fresh install on my local machine and now when switching pages I don't see nothing wrong, it was probably when I migrated from sqlite to mysql that something went wrong, sorry about this
