### ISSUE TITLE
Deleting a project in admin-dashboard

### ISSUE THREAD

**Issue by SchoofLux** [spiral-project/ihatemoney#1094]
I’m still experiencing the same issue as #978. I cannot delete any project from the Admin dashboard.
I’m using docker which works perfectly otherwise.
Problem occurs with SESSION_COOKIE_SECURE set to True or False. No difference.

**Comment by almet** [comment]
Thanks for opening an issue here :-) This needs some more investigation then !

**Comment by almet** [comment]
Okay, this is due to the changes in how project deletion works (https://github.com/spiral-project/ihatemoney/commit/db982572aaf0ac474d2778c3dcd1aac33581feb3).
