### ISSUE TITLE
Captcha not working on german website

### ISSUE THREAD

**Issue by oldnick1818** [spiral-project/ihatemoney#1117]
The correct answer didn't work, neither with uppercase nor lowercase for the first letter. I got the read banner, telling me to do the Captcha again. When I switched to the english site it accepted the answer and worked just fine.
Problem occured in Firefox 107.0.1 on Mac.

**Comment by chestnutFan** [comment]
Interesting. Looks like it's the same with issue #1126. I'd like to take this issue if nobody is working on it.

**Comment by Glandos** [comment]
Duplicates of #1060. Fixed by #1061.

The hosted version needs to be updated, but this involves a lot of other updates for now.
