### ISSUE TITLE
Creating a new project (in the hosted version) in German does not work

### ISSUE THREAD

**Issue by schuhwerk** [spiral-project/ihatemoney#1126]
Thanks for your work on ihatemoney! Lovin it :)

I'm always coming back to the Captcha question (if my language is set to German):
![image](https://user-images.githubusercontent.com/865652/212623837-c5b96831-ae55-472c-9b46-a63b921099cf.png)

No issues if I change the language to English.

**Comment by chestnutFan** [comment]
Interesting. Looks like it's the same with issue #1126. I'd like to take this issue if nobody is working on it.

**Comment by Glandos** [comment]
Duplicates of #1060. Fixed by #1061.

The hosted version needs to be updated, but this involves a lot of other updates for now.
