### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by azmeuk** [spiral-project/ihatemoney#1130]
I hate money too, and I also hate having to check ihatemoney on a regular basis to see if there is something new (though I really appreciate ihatemoney).

I suggest implementing RSS feeds of the bills for each projects.

What do you think?

**Comment by zorun** [comment]
Interesting idea. It would require authentication though, do RSS client typically support that?

**Comment by azmeuk** [comment]
I suppose this would be simple to rely on the [HTTP authentication layer](https://developer.mozilla.org/en/docs/Web/HTTP/Headers/Authorization).

I have seen some websites (like https://www.nextinpact.com/) generating long secret URLs for their RSS feeds. Each (paying) user is generated a long personal unguessable URL for the RSS feed of the articles. Users can invalidate and regenerate an URL as they want.

**Comment by azmeuk** [comment]
I attempted a basic implementation with #1158

However, we may want to handle [ETag](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/ETag)/[If-None-Match](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/If-None-Match) and [Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified)/[If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) HTTP headers to avoid generating the whole feed when the content has not changed between two client requests.

However in order to be able to do this, this would be needed to save the *last update datetime* for projects. This date would be updated at each bill addition/edition, and would be used to generate the `ETag` and `Last-Modified` headers.

As this would need a migration, I would like to discuss this before I open a PR. Would you be OK with adding such a field on `Project` or do you think the feature is not needed?

**Comment by azmeuk** [comment]
Fixed by #1158

**Comment by azmeuk** [comment]
Out of curiosity, do you have a schedule for deploying v6.1 on ihatemoney.org?

**Comment by almet** [comment]
@azmeuk It's not planned, but I need to do it at some point :-) I've planned some time for it this friday.

**Comment by almet** [comment]
@azmeuk Just deployed it!
