### ISSUE TITLE
ALLOW_PUBLIC_PROJECT_CREATION + other password than admin

### ISSUE THREAD

**Issue by 18info** [spiral-project/ihatemoney#1154]
Hi! :)

Is there a way to set an other password than the admin one to protect IhateMoney in "non public" mode ?
For now:
```ini
ADMIN_PASSWORD = "pbkdf2:sha256:260000$[…]"
ALLOW_PUBLIC_PROJECT_CREATION = False
ACTIVATE_ADMIN_DASHBOARD = False
```
Is it the best I can do?

Many thanks!

**Comment by zorun** [comment]
What do you mean by "protecting" and "non-public"?

The admin password is used for two things:

- the admin dashboard
- the ability to create projects when ALLOW_PUBLIC_PROJECT_CREATION is False

It is completely independent from the private code of projects. So, even with ALLOW_PUBLIC_PROJECT_CREATION = False, your projects definitely have a different "password" (we call that private code) than the admin password.
