### ISSUE TITLE
The captcha is not clear (project creation)

### ISSUE THREAD

**Issue by Arunnsda** [spiral-project/ihatemoney#1156]
While creating the new project, enter mandatory fields and select real currency as the Petro Dollar system doesn't allow for the creation of new projects.
step to reproduce.
launch Application
Create new project.
select currency as Petro dollar

**Comment by greedybro** [comment]
From what i tested -> The question `Euro or Petrodollar?` seems to be the captcha. The error message is kind of explicit when you choose `petrodollar`, even though i admit it is not instinctive.

You can also validate by setting the captcha to false and then the question is not asked at creation.

That said, Petrodollar is not a reel currency, it's more a concept. You can customize the currency of your project after creation in its settings (not set by default), but no Petrodollar here, just boring old US dollar :)
