### ISSUE TITLE
Unsupported hash_type

### ISSUE THREAD

**Issue by besendorf** [spiral-project/ihatemoney#1165]
I generated an admin hash with `ihatemoney generate_password_hash` and got this error when I try to log in in the web app
`ValueError: unsupported hash type "pbkdf2:sha256:260000`

**Comment by Glandos** [comment]
Hi!

Sorry for the late answer. What is your current Python version, IHateMoney version (or git commit) and dependencies versions?

**Comment by zorun** [comment]
@besendorf Is this the same issue as #1169 ?

**Comment by besendorf** [comment]
Yes I think so. It worked now without quotes and double $$

**Comment by zorun** [comment]
Cool!
