### ISSUE TITLE
Documentation no longer updates automatically

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#1185]
It says "Failed" on https://readthedocs.org/projects/ihatemoney/builds/

This happened before in #653

Maybe we should update documentation from the Github CI, so that we would be aware when it breaks.

**Comment by zorun** [comment]
Still not working, different issue: https://readthedocs.org/projects/ihatemoney/builds/21301509/

@Glandos apparently the sphinx-rtd-theme from readthedocs does not support Sphinx 7:

- https://github.com/readthedocs/readthedocs.org/issues/10279
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1463

I see you updated Sphinx #1172 because of docutils, why do we need a newer docutils?

**Comment by zorun** [comment]
To be honest (it's definitely not against you @Glandos ), I'm really fed up with dependabot trying to update everything to the latest version, even if we don't actually need it... (e.g. not for security issues)

But maybe that's just me being conservative :D

**Comment by Glandos** [comment]
I think I should also refrain from clicking on "Update" each time I am notified of something just to have a dopamine shot.

I think that:
- updating "real project" dependencies is good. E.g. SQLAlchemy, Flask, etc.
- updating "dev" dependencies should be done more peacefully. Breaking the build process is easy, fixing it is tedious, and we don't spend enough time on this project for that.

For this specific issue, I am bit hesitant. We can downgrade Sphinx/docutils after all, it won't impact any users. It seems that waiting for a new release of sphinx_rtd_theme is like waiting for the rain in the hot summer of Spain: it will happen, you don't know when.

**Comment by zorun** [comment]
@Glandos do you have time to downgrade Sphinx to fix this issue?
