### ISSUE TITLE
Canceling autocomplete with 'esc' cancels the bill too

### ISSUE THREAD

**Issue by QuentinRoy** [spiral-project/ihatemoney#125]
This issue is related to #124.

I dont think it is possible to check if the browser is displaying autocomplete propositions (I could not find how).
Thus, there is three alternatives to solve this bug:
1. Removing autocomplete. However #124's discussion raises some objections against this solution)
2. Removing bill cancelation when the user presses the escape key. It is probably not what we want either.
3. Replace browser's autocomplete with an autocomplete plugin that we manually provisioned and that we can control (e.g. https://jqueryui.com/autocomplete or http://twitter.github.io/typeahead.js). Obviously more complicated but I think that may actually be a good idea.

Any preferences?
If option 3, any techno preferences?

**Comment by almet** [comment]
I think option 2 is what makes the most sense here.

**Comment by almet** [comment]
adding data-keyboard="false" would be option 2.

**Comment by indatwood** [comment]
This is fixed thanks to @tombiju's work :-)
