### ISSUE TITLE
Feture Request: Add the option to assign pro-rata payments to participants

### ISSUE THREAD

**Issue by thinkbig1979** [spiral-project/ihatemoney#1252]
We recently spent the weekend away with the family.
There were 5 families totaling 17 people, and we wanted each family to pay a their fair share according to how many people there were in that family with costs being split equally per head.

In order to achieve this I added all parents and kids as participants, and then added the payable amounts of each family member up to arrive at a rate for each family. 

So essentially, you want to know 
1. How many total people sharing the cost?
2. On behalf of how many people is each paying participant settling the bill?

It would be great to be able to add only one participant per family and then assign a rate split to that participant. Eg. 
Total participants = 17
`Family 1`: settling on behalf of     `5`  participants
`Family 2`: settling on behalf of     `3` participants
`Family 3`: settling on behalf of     `4` participants
`Family 4`: settling on behalf of     `4` participants
`Family 5`: settling on behalf of    `1` participants

Similar to the request for adding percentage I suppose, but doing it this way seems more intuitive to me as it relates directly to the real world and you don't have to calculate and fill in a percentage.

**Comment by zorun** [comment]
Actually, this use-case is already covered by setting weights on participants. That is, assuming that everybody stays for the whole duration (otherwise, @almet is pointing to the right discussions)

**Comment by thinkbig1979** [comment]
Thanks very much! :-)
