### ISSUE TITLE
Can't access my project anymore, says it doesn't exist

### ISSUE THREAD

**Issue by PolpredoX** [spiral-project/ihatemoney#1265]
Hi,

Sorry if I'm in the wrong place but I didn't know where else to post. I've been using I hate money for a year with my roomates and it worked just fine. I tried to connect to it this morning and the webpage told me "error delay". I went on the website itself and when I'm trying to connect to my project - the site tells me that it doesn't exist. 
I didn't save any of the informations from the project and of course it happends at a moment where there's movement in my flat and people need their money... Is there anyway to recover the project ((name: herboloc) from the hosted version of Ihatemoney? Or do I have to make a new one and lose all my datas?

Thanks in advance for any help you could provide !

Have a nice day. 

PdX

**Comment by almet** [comment]
Hi, I suppose you're using the hosted version at https://ihatemoney.org.

I've checked on the database but couldn't find any project with this id. Are you sure about the id ? (you can find it in the email that was sent to you when creating the project), or in the URLs you have visited for this project in the past.

Thanks.

**Comment by PolpredoX** [comment]
Hi,

Thanks for the answer !

Here is the mail I received when I created the project :

Salut,

Vous venez de créer le projet "Herboloc" pour partager vos dépenses.

Vous pouvez y accéder ici : http://budget.tila.im/herboloc/ (l'identifiant est herboloc).
Si vous voulez partager ce projet avec vos amis, vous pouvez soit leur transmettre l'identifiant et le code d'accès, soit leur envoyer une invitation personnelle grâce au lien suivant :
http://budget.tila.im/herboloc/invite

Faites-en bon usage !


It worked at least until last sunday. When I last checked the account.http://budget.tila.im/herboloc/ is the Url I used.

Thanks !



________________________________
De : Alexis Métaireau ***@***.***>
Envoyé : vendredi 17 novembre 2023 11:37
À : spiral-project/ihatemoney ***@***.***>
Cc : PolpredoX ***@***.***>; Author ***@***.***>
Objet : Re: [spiral-project/ihatemoney] Can't access my project anymore, says it doesn't exist (Issue #1265)


Hi, I suppose you're using the hosted version at https://ihatemoney.org.

I've checked on the database but couldn't find any project with this id. Are you sure about the id ? (you can find it in the email that was sent to you when creating the project), or in the URLs you have visited for this project in the past.

Thanks.

**Comment by almet** [comment]
Thanks for the info.

> It worked at least until last sunday. When I last checked the account.http://budget.tila.im/herboloc/ is the Url I used.
>
> Thanks !

Unfortunately, I'm not the person behind tila.im. I believe it's hosted by @florencebiree, which might be able to help you out.

Your best bet is to look for tila.im docs and find somewhere to contact there, and/or wait.

My personal guess is that they currently have problems with their servers as I can't reach the info pages at the moment.

I'm closing this as I can't do anything for you unfortunately.

**Comment by florencebiree** [comment]
Hi, @PolpredoX 

Glad to know your using my server for your accounts, and yes, the server had an internet failure since yesterday evening, and I solved in this afternoon (replacement of the power supply for one router).

This service on my server is open, so you may not have read the term of services before using it:
in French: https://tila.im/doc/apropos.html
automated english translation: https://tila-im.translate.goog/doc/apropos.html?_x_tr_sl=fr&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp

When there is a failure, don't hesitate to communicate with me (but not by mail - it the server doesn't work, my email neither) : https://florence.biree.name/contact/
And if you send me your e-mail address, I can add you to the mailing-list with updates about how the server work, failures, etc (in French).

**Comment by PolpredoX** [comment]
Hi Florence,

Thank so much for your answer. I didn't know if I fucked up on my end or if it was a server issue. Thank you for responding and taking time to fix the issue!
I read the à propos and I didn't realize "I hate money" on your server was reserved to people living around Cazères! I'm sorry if I overstepped a boundary. The service we were using with my roommates went down last year and after a quick search, I realized this was the better option for us. But do not hesitate to tell me if we need to leave the server. I will take the date and find something else.
Et en fait je viens de réaliser que si l'à propos est en français, je peux écrire en français... Déso, je comprends vite mais faut m'expliquer longtemps. Merci pour les liens et oui je veux bien être mis dans la boucle des mails, si encore une fois c'est pas juste pour les gens de Cazères.
Dans tous les cas, merci pour tout aujourd'hui ! Et merci d'avoir mis en ligne ce service.

Bonne nuit et content de t'avoir rencontré par mail !

PdX


________________________________
De : Florence Birée ***@***.***>
Envoyé : vendredi 17 novembre 2023 15:59
À : spiral-project/ihatemoney ***@***.***>
Cc : PolpredoX ***@***.***>; Mention ***@***.***>
Objet : Re: [spiral-project/ihatemoney] Can't access my project anymore, says it doesn't exist (Issue #1265)


Hi, @PolpredoX<https://github.com/PolpredoX>

Glad to know your using my server for your accounts, and yes, the server had an internet failure since yesterday evening, and I solved in this afternoon (replacement of the power supply for one router).

This service on my server is open, so you may not have read the term of services before using it:
in French: https://tila.im/doc/apropos.html
automated english translation: https://tila-im.translate.goog/doc/apropos.html?_x_tr_sl=fr&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp

When there is a failure, don't hesitate to communicate with me (but not by mail - it the server doesn't work, my email neither) : https://florence.biree.name/contact/
And if you send me your e-mail address, I can add you to the mailing-list with updates about how the server work, failures, etc (in French).

**Comment by florencebiree** [comment]
Pas de soucis que tu ne sois pas sur Cazères, pour ce service-là en tout cas. Cette règle m'a surtout permis d'éviter des personnes qui étaient assez reloues, mais pour I hate money, il n'y a pas de création de comptes, tout est ouvert.

Par contre, pour que je t'ajoute sur la liste e-mail, je veux bien que tu me donne ton adresse en m'écrivant en privé sur mon mail : https://florence.biree.name/contact/

Là on échange via les tickets github, du coup je n'ai pas ton adresses mail ;)

Bonne fin de journée,
Florence
