### ISSUE TITLE
Worker process raises TabError 

### ISSUE THREAD

**Issue by Gbury** [spiral-project/ihatemoney#127]
I tried to run the server on my machine and ended up with a rather long list of TabErrors (full error output available at: http://gbury.eu/public/error_log.txt ). It seems to be an error that came with python3, which forbids use of both tabs and spaces for indentation.

**Comment by ametaireau** [comment]
Ah yeah, it's not compatible with python 3 I believe. I'll be happy to review / merge changes to go in this direction though!

**Comment by almet** [comment]
See #157
