### ISSUE TITLE
Apache instructions

### ISSUE THREAD

**Issue by tigre-bleu** [spiral-project/ihatemoney#128]
It would be nice for the "average administrator" to have a document explaining the steps to install the application with apache.

The curent steps are imho not so easy to understand.

**Comment by ametaireau** [comment]
Hi!

I don't install with Apache so I cannot really help here. However, I can paste the NGINX configuration and put it in some settings if that makes it easier for you and others.

Otherwise, would you like to contribute a documentation about how to deploy with Apache?
