### ISSUE TITLE
E-Mail with the internal IP

### ISSUE THREAD

**Issue by HawkM8** [spiral-project/ihatemoney#1289]
Hello,

I´m using this great tool in a docker container. Infront of that I have a firewall running as a reverse Proxy. That is all running perfectly fine.
 
But if there is an email created, e.g. for a new project, the link is always just the internal IP instead of the external domain.
Is there an option to set the external Domain globally for all the email templates?

**Comment by almet** [comment]
Hey, maybe try using `SERVER_NAME`as defined here https://flask.palletsprojects.com/en/3.0.x/config/#SERVER_NAME

**Comment by almet** [comment]
Closing, let us know if you need more help :-)
