### ISSUE TITLE
CSRF Token: The CSRF tokens do not match.

### ISSUE THREAD

**Issue by queball1999** [spiral-project/ihatemoney#1304]
Has anyone seen this error before? I have the docker image running in a Proxmox LXC.

I was able to access the web server from the local IPv4 address but I keep getting this error when trying to create a project.

![image](https://github.com/spiral-project/ihatemoney/assets/57122349/2cd72310-1465-49e3-9cdb-510a92c52cca)

**Comment by zorun** [comment]
If you run over plain HTTP, you probably need to disable secure cookies: https://ihatemoney.readthedocs.io/en/latest/configuration.html#session-cookie-secure
