### ISSUE TITLE
Feature request: users and permissions

### ISSUE THREAD

**Issue by alfredonodo** [spiral-project/ihatemoney#1310]
Hello,
I am looking for an application that is able to share expenses between a group of people. I found your solution and it seems very good.
However, I read [here](https://ihatemoney.readthedocs.io/en/latest/security.html) that you do not provide users. If a user accidentally or voluntarily deletes/changes all the data, how can this be prevented? Are you going to add users and permissions so that each user can only edit his own data?
Thank you

**Comment by almet** [comment]
Hi, and thanks for your interest. You are correct, we do not provide users, and we require that user trust each other.

We have a book-keeping mechanism, that you can turn on, which makes it possible to see who did what. We do not plan to add permissions on the project.

Cheers :-)

**Comment by almet** [comment]
For more information on the direction taken by the project, [you can read this](https://github.com/spiral-project/ihatemoney?tab=readme-ov-file#current-direction-as-of-2024)
