### ISSUE TITLE
[Question] HOW to access the admin dashboard ?

### ISSUE THREAD

**Issue by T0MuX** [spiral-project/ihatemoney#1316]
Hi, i'm really sorry maybe this is a dumb question for all of you. But i'm tired to looking everywhere, try anything, without any result.

Either the documentation is not enough clear, either i'm dumb.

**How to access to the admin dashboard, please ?**

For the record, I start my container with this command :
`docker run -d -p 8090:8000 ihatemoney/ihatemoney -e ACTIVATE_ADMIN_DASHBOARD=True -e ADMIN_PASSWORD=pbkdf2:sha256:260000$hOpIMG3FrnUswEuK$99e40fd588c100f1830538f7ed4eeefd9281d72153f4b8b3c8101bf900f99e6e -e ENABLE_CAPTCHA=true -e BABEL_DEFAULT_TIMEZONE='Europe/Paris' -e DEBUG=False -e ACTIVATE_DEMO_PROJECT=False`

I generated the hash following the documentation.
I tried "admin", and "root" as project id, and my chosen password in the password field. Doesnt work, it gets me to the creation of new project. I really don't understand how to access the admin dashboard. I also tried to create a project and explore inside, but didn't found anything more.

**Comment by almet** [comment]
Hi, there is no dumb question, just not enough documentation :-)

You can access the admin dashboard at `/admin`

HTH,
Alexis
