### ISSUE TITLE
Split emails on new line, coma, and semi-column and trim them.

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#133]
In the invitation form, it's possible to enter a list of emails. Currently, they are only coma-separated, but they could also be split with new lines and semi-columns.

Also, they could be trimmed.

**Comment by almet** [comment]
That would be a welcome addition!

**Comment by JoseAntonioTorre** [comment]
Could you describe this issue?

**Comment by almet** [comment]
@JoseAntonioTorre I've just updated the description, that should make things a little easier to grasp.

**Comment by JoseAntonioTorre** [comment]
Something like this could be enough? 
![Screenshot_20191015_004113](https://user-images.githubusercontent.com/1927763/66787601-99b15280-eee4-11e9-92cc-d52b207f607d.png)

**Comment by JoseAntonioTorre** [comment]
If that is enough I can send the PR.

**Comment by Natim** [comment]
I guess it can help. Can we copy paste a list of email comma separated as well as tab or new line separated?

**Comment by JoseAntonioTorre** [comment]
Now, I have configured it to accept only commas. In my opinion, having multiples ways to insert the same information is not a good idea in terms of usability. I can extend it to allow entering with ';'.
The PR consists of an input that actuates as normal and when you enter a ',' it will envelope it in a tag.

**Comment by Natim** [comment]
The goal is not to have multiple ways to enter the thing but to handle copy paste from different source.

**Comment by JoseAntonioTorre** [comment]
Ok, I have read the title and I don't see it there.
So besides the functionality that I have already developed, you want to have the option to copy text from a comma-separated list or any of the format you mention before and make it compatible with this system right?

**Comment by Natim** [comment]
We don't need to support all of them, I guess handling coma and newlines would be enough.

**Comment by JoseAntonioTorre** [comment]
Ok, this afternoon I will work on it and if I have time I will send the PR :)
