### ISSUE TITLE
Hello ! I have added the Azerbaijani translation and made pull request but it gave me one error. Could you review ?

### ISSUE THREAD

**Issue by ferid333** [spiral-project/ihatemoney#1335]
Hello ! I have added the Azerbaijani translation and made pull request but it gave me one error. Could you review ?

**Comment by ferid333** [comment]
What is the reason for the failure when I have made pull request ?

**Comment by almet** [comment]
Hi, thanks Farid for your PR. The project is only run by people volunteering their time, and nobody had a chance to have a look at the reason of the failure.

I understand why and how this can be frustrating, but opening more messages will not get you more attention, unfortunately. Somebody will review your PR when one finds the time.

Thanks for your understanding,
Alexis

**Comment by ferid333** [comment]
Thank you
