### ISSUE TITLE
Be able to configure the number of person in the person list.

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#134]
When going with couple, you want to count 2 people for some names and 1 for some other one.
Another way do to that would be to merge group people on the settle page to remove money transfert between people of the same couple for instance.

**Comment by almet** [comment]
I believe this is a dupe of https://github.com/spiral-project/ihatemoney/pull/131.  Closing.

**Comment by Natim** [comment]
Yes it might be, should we merge it?
