### ISSUE TITLE
Between Members Transfer registration

### ISSUE THREAD

**Issue by QuentinRoy** [spiral-project/ihatemoney#139]
Another common type of transaction is transfer between members: (e.g. Sarah gave 10 euros to George).
This type of transaction is actually almost required if one wants to zeroes her balance before leaving for example.

One trick that can be used (and that I saw myself using several times) is to register a bill in the form of Sarah paid 10 for George (only). However, it really looks like a trick. I am wondering if we should not provide a more obvious way to do this.

**Comment by almet** [comment]
I don't really see this as a trick: if Sarah paid 10 for George, well, it seems easy enough, isn't it? I'm closing for now, feel free to reopen if you disagree.
