### ISSUE TITLE
Make 'Private code' and 'Email' optional

### ISSUE THREAD

**Issue by tomfitzhenry** [spiral-project/ihatemoney#140]
When I create a new project, I just want to give my shared expenses a name (e.g. "Christmas 2015 holiday"), and get started. The private code could be generated, and included in the URL, which I'll send around to friends via our existing comms channels (whatsapp or whatnot). What's the rationale for requiring a secret code and email address?

**Comment by almet** [comment]
That's actually a good idea! I would be thrilled to see the project moving forward in this direction. Do you want to work on it? Do you need some guidance?

**Comment by almet** [comment]
Bump ! Would you like to work on such an addition?

**Comment by almet** [comment]
The problem I see with such an approach is that you couldn't find your way back to your project if you lose the info. Having the email is just for this purpose. Closing for now, feel free to reopen if needed.
