### ISSUE TITLE
Add NOT NULL to many fields

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#143]
_budget/models.py_ is quite lazy about SQL required fields.

Most of fields are mandatory but not marked as such in the SQL scheme.

The TODO is to add `nullable=True` to relevant several fields in models.py

**Comment by leonardofreitas-ciandt** [comment]
I'll gonna take this one, ok? @almet

**Comment by lndamaral** [comment]
I'm gonna take this one, ok? @almet

**Comment by almet** [comment]
Sure, go for it!

**Comment by lndamaral** [comment]
Hey @almet, It won't be possible to do this change due to SQLite limitation (https://sqlite.org/lang_altertable.html)

When setting `nullable=False/True` in the model file, the migration creates an "alter column" statement which, as you can see on the link above, is not possible to perform it on SQLite. On Postgres, it would be possible, but considering that SQLite is the default one (hardcoded, dockerfile,...) this is limiting this change.

Thoughts?

My suggestions:

- Change model file setting the expected nullable references for each field. But doing that, I'll need to remove all other migrations files.  

Please let me know what do you think.

**Comment by eMerzh** [comment]
you could do the migration but apply the alter only for non sqlite db no?

**Comment by indatwood** [comment]
Hi @lndamaral !

Are you still keen to work on this?

**Comment by neilZon** [comment]
Hi, is this still up for grabs?

**Comment by Glandos** [comment]
Hi @neilZon, yes, you can have a look at this :) Feel free to ask any question!

**Comment by sahven** [comment]
Hi, I'm new to open-source dev. I'd like to take up this task if it's still open. If yes, please let me know how and where should I start?
Thanks

**Comment by JocelynDelalande** [comment]
> Hi, I'm new to open-source dev. I'd like to take up this task if it's still open. If yes, please let me know how and where should I start?

Hello @sahven and welcome around and… in open-source world ! :unicorn: :rainbow: 🌼 !

We use git and pull requests to receive contributions. 

Are you familiar with git and pull request ?

Rough steps are :

- create a fork of this repository
- clone your fork
- create a git branch dedicated to this ticket
- commit locally on that branch (one or several commits)on your fork, a branch dedicated 
- push this branch to your fork
- create a pull request of your branch on this repository (spiral-project/ihatemoney).

You may also want to look at [our contributing guide](https://ihatemoney.readthedocs.io/en/latest/contributing.html).

Does that helps ? Feel free to ask further questions here :).

**Comment by damonphilipross** [comment]
Hey this looks still open mind if I work on it?

**Comment by almet** [comment]
Yes, please open a pull request and let's see :-) Thanks!

**Comment by ajjayymahato** [comment]
Is this repo a part of hacktoberfest?

**Comment by Sayantan19** [comment]
I would like to give it a shot! Is the issue still open?

**Comment by Glandos** [comment]
@ajjayymahato No, it is not.
@Sayantan19 yes, of course it is still open. You can have a try if you want.

**Comment by Pmeet** [comment]
Hi, I want to work on this issue. I have been searching for issues related to Django as I love it and have been working on it for quite some time.

**Comment by zorun** [comment]
Closing, this doesn't seem to be an issue in practice. Also, if sqlite doesn't behave the same as the other databases, there is a risk of introducing more complexity.

See the current direction about simplicity: https://ihatemoney.readthedocs.io/en/latest/contributing.html#current-direction-as-of-2024
