### ISSUE TITLE
http*s* hosted website is down

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#146]
From [doc](https://ihatemoney.readthedocs.io/en/latest/api.html) : 

> If you don’t want your credentials to pass in clear trought the network, you can use the ssl endpoint at https://ihatemoney.notmyidea.org

That is a good idea :)… However, https://ihatemoney.notmyidea.org/ does not work.

**Comment by JocelynDelalande** [comment]
Closing, the issue was barely that domain changed, see #147

**Comment by almet** [comment]
It's now HTTPS on ihatemoney.org
