### ISSUE TITLE
Update to bootstrap 4

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#168]
we are currently using bootstrap2. Bootstrap 4 is currently alpha, but close to beta, which will be followed by a final release.

So I propose to jump directly to bootstrap 4 (of coulrse, we may wait for final release of BS4 to merge such a PR). BS4 introduce nice things like the use of flexbox for positioning.

I started to work on it ; nothing that I'd be proud enough to show code yet, but here are some screenshots, as apetizers ;-)

![screenshot-localhost 5000 2017-01-29 17-10-44](https://cloud.githubusercontent.com/assets/429633/22405626/f0fd5d90-e645-11e6-8a65-391c6e3065ab.png)
![screenshot-localhost 5000 2017-01-29 17-11-48](https://cloud.githubusercontent.com/assets/429633/22405627/f1007764-e645-11e6-8d62-1773e7934d62.png)

I'm trying to be quite neutral on that upgrade, not revamping the whole design, keeping the spirit of previous designs. But you'll notice some changes (see forms and their labels on home page), this is because I have the responsive version in mind that require some changes (see #113 ).

More comming soon…

**Comment by aavenel** [comment]
I strongly approve this ! If I can help with something, let me know.

**Comment by JocelynDelalande** [comment]
@aavenel I'll let you know when it will come to testing :)

Note that BS4 means dropping support for some old browsers like IE9.

**Comment by JocelynDelalande** [comment]
Notes for myself, what will be changed with the BS4 PR:

- better factorization of templates
- fix moving elements (ex: try switching from project page to home page, things in sidebar are moving)
- improve readability
- fix misaligned elements
- make more use of BS grid system
- responsive design

I'm afraid my git log will be quite non-atomic :-s

**Comment by almet** [comment]
That looks exciting, thanks for your work on this :)

**Comment by JocelynDelalande** [comment]
@aavenel actualy, I'm pretty close to something on this topic, but responsive could come in a second time, so I won't include responsive things in this PR ; however it will be made easier by BS4.

So, to reconsider your question:

> I strongly approve this ! If I can help with something, let me know.

Is the adding of responsive code for small srceens (using BS4) something you would like to code ?

**Comment by aavenel** [comment]
@JocelynDelalande I've close to no experience in this kind of development, but I can give it at try. Can you push a WIP PR so we can have a look at the code ?

**Comment by almet** [comment]
This is now fixed by #172
