### ISSUE TITLE
Do a complete review to remove XSS

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#175]
It's highly probable, even after @aavenel fixed on of those (see #173)  that XSS are still possible in Ihatemonney.

Anyone for a complet review ? See @aavenel comment here : https://github.com/spiral-project/ihatemoney/issues/173#issuecomment-279854242 for some leads on how to fix those.

**Comment by aavenel** [comment]
This issue is a bit too generic. I think we can close this one.
