### ISSUE TITLE
Rename delete to deactivate

### ISSUE THREAD

**Issue by Jojo144** [spiral-project/ihatemoney#177]
I suggest renaming 'delete' / 'supprimer' a person by 'deactivate' or 'disable' / 'désactiver' it. Otherwise, it is very hard to know that it is possible to reactivate it afterwards.
By the way, this feature is very nice!

**Comment by almet** [comment]
Hi, would you like to contribute the change ?

**Comment by Jojo144** [comment]
I know the change is less that 5 lines so I could do that.
But I didn't manage to setup the test environment in few minutes.
So I prefer to decline for the moment, I am very busy those days.
I'll do it later if nobody act before ...

**Comment by Jojo144** [comment]
Hum... I am sorry to reopen this issue but, in fact, I better understood what do this button in the meantime.
This button actually *delete* the user if its total is 0. If it is not, the user will be *deactivated* until its total reach 0, in that case it will be automatically deleted.
I thus propose to revert this commit and change the message "User ... has been deactivated." to something like " User ... hes been deactivated. It will be deleted if its total reach 0."
I should document that, fore sure!

**Comment by JocelynDelalande** [comment]
The user is just hidden then, but remains in database doesn't it ?
