### ISSUE TITLE
Use tox to allow devs to test against multiple python versions

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#184]
Now that we have python3 compatibility…

Currently, [travis tests against multiple python versions](https://github.com/spiral-project/ihatemoney/blob/master/.travis.yml#L2-L4). But locally, the developper does not have the tools to run the test suite against different python versions.

[Tox](https://tox.readthedocs.io/en/latest/) may be the way.

**Comment by almet** [comment]
Yes, tox is the graal here. See how it's done in the Kinto project: https://github.com/Kinto/kinto/blob/master/tox.ini
