### ISSUE TITLE
Have a way to externalise the settings

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#187]
Currently, the settings file needs to be in the same directory as the source, which is a problem when you want to package it properly.

We've yet to find a solution for this, any help is welcome on the topic :)

**Comment by 0livd** [comment]
We could use instance folders for this and put the configuration in something like /etc/ihatemoney/ihatemoney.cfg
http://flask.pocoo.org/docs/0.12/config/#instance-folders

**Comment by almet** [comment]
Thanks for the pointer. It seems that the current source code uses the `FLASK_SETTINGS_MODULE` environment variable to define where the settings module should be, so it might just already work, but this has yet to be verified in practice.
