### ISSUE TITLE
Better document SECRET_KEY tunning on a production instance.

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#195]
Currently, we don't warn boldly people installing ihatemoney to change `SECRET_KEY` with a random string. Thus, blindly following README leads to insecure installation with a SECRET_KEY set to *tralala*.

We must improve doc on that topic.

**Comment by almet** [comment]
What we did on kinto was to provide à tool to generate the settings file maybe we should do the same here ?

**Comment by JocelynDelalande** [comment]
> What we did on kinto was to provide à tool to generate the settings file maybe we should do the same here ?

Sounds cool :-)

We could use a `manage.py` subcommand.
