### ISSUE TITLE
Document the settings

### ISSUE THREAD

**Issue by 0livd** [spiral-project/ihatemoney#212]
We should document each setting in the ``Configure it`` section of the readme, especially after the recent addition of new ones (``ACTIVATE_DEMO_PROJECT`` and ``ADMIN_PASS ``)

**Comment by almet** [comment]
I concur. In general, I believe we would benefit from a review of our documentation in general, so it's more comprehensive.

**Comment by JocelynDelalande** [comment]
Wild idea : maybe we should extend the sphinx doc, instead of bloating the README ?

**Comment by 0livd** [comment]
@JocelynDelalande Yes this could be the way to go. It feels like everything can fit in the readme since there is not much to say after all, but keeping it concise and easy to read is a difficult exercise...
We could keep the most important stuff like ``Make it run`` in the readme and move the rest in the sphinx doc

**Comment by almet** [comment]
Yes, or we could just have a small readme which just redirects to the documentation, with a link, and maybe add a few captures so people can see what the project looks like without having to test it themselves.
