### ISSUE TITLE
Ideas for enhancements

### ISSUE THREAD

**Issue by FabriceSalvaire** [spiral-project/ihatemoney#214]
**What is the use case ? :**  Manage expenses for (sport) outdoor outings. There are certainly a  large need on this topic.

_We are also using Google doc  (document and calc application) to organize the outings, Drive for photos, Doodle for meeting planning, and a CMS web site._ 

**Wanted features :**
1. Basic HTTP Authentication : I don't want that script kiddy's hacker play with it, **done on my fork**
2. Implement a basic Workflow to know where we are : all participant as approved the expenses (an approved check box - mandatory), then we can proceed to the payment (a payed check box - informative ...)
3. Fix layout on smartphone
4. CSV export

**Must to have features:**
* Expense Category (transport, food, hotel) to compute expense statistics : full total, by participant, by day.

**Bad ideas ? :**
* Manage bank details in the application
* Smartphone application

**I suggest a plugin approach to handle different needs.**

**Comment by almet** [comment]
Hi, thanks for taking the time to submit your ideas in the bug tracker!

However, It seems that you have many different ideas here, and we try to keep track of the suggestions in a different ticket for each. Hence, I will close this very ticket, but please don't consider that we are rejecting your ideas. If you want us to discuss them, the best way to do so is to open a different ticket for each.

In general, a bunch of the things you're proposing here have already been discussed, see for instance #55 #176 and #113.

Thanks,
Alex
