### ISSUE TITLE
Need to unzoom on firefox mobile to add bills

### ISSUE THREAD

**Issue by pyg77** [spiral-project/ihatemoney#219]
Firefox for Android 53.0.2

When I want to add a new bill on firefox mobile, the popover is opening as expected, I enter somehhing in the "What?" field (producing an automatic zoom on the popover). Then when I want to enter something on another field (like the payer field), nothing is happening. I can't even validate or close the popover.

Solution found: unzoom to max, by unpinching on the screen, then target carefully the wanted field.

**Comment by almet** [comment]
Thanks for writing this bug report! I've yet to understand why this happens. I first thought that this was due to the fact that I mis-deployed the latest changes on https://ihatemoney.org, but it seems that I did everything well there.

When I try to access the project using my firefox browser on desktop and go in the "mobile" view, everything seems to behave like it should. Weird.

Any idea about where this could come from? cc @Phyks

**Comment by Phyks** [comment]
Yes, I noticed it as well on my instance. Not sure where it comes from, might be related to my latest PR. I'll try to have a look. 

Previous behavior was unusable on mobile devices. Hopefully we will converge with a responsive UI :)

**Comment by pyg77** [comment]
Please note that everything is working well on chrome/android (58.0.3089.83)

**Comment by Phyks** [comment]
> Please note that everything is working well on chrome/android (58.0.3089.83)

Oh, that explains why other users on the instance are not seeing this issue. I just noticed it two days ago, and was thinking it was just a cache issue, or some bug on my phone. But you noticing it also means it is really a bug (either in ihatemoney or Firefox for Android).

Not sure how blocking this is for you at the moment? The fact that one could zoom on mobile UI is quite disapointing for me. https://github.com/spiral-project/ihatemoney/pull/213 just fixed basic CSS to make it usable on mobile (even if not the best experience possible) as it was really blocking for me, and I want to take some time to get something truly responsive.

**Comment by almet** [comment]
@pyg77 Can you confirm this is solved via the latest commit ? It is currently deployed on https://ihatemoney.org, please update your cache (ctrl + f5 should be enough), as we're not doing anything fancy to force refresh the CSS files with every updates ;))

**Comment by pyg77** [comment]
Not totally :-/

(can't do ctrl+f5 on a mobile, but I have emptied the cache ;) )

Steps to reproduce on Firefox 53.0.2
1. Go on the demo project
2. scroll down to add a bill, and click "Add a Bill"
3. tap on "What?" field, then input something on "what?" field
4. tap on "Payer" scrolldown.

Nothing happen when I tap on user scrolldown.
Expected behavior: list of users appear, and I can select one.

Solution found: pinch on the screen to zoom, then unzoom (only backgroung viewport is resized), then tap on "What?" scrolldown. List of users appears.

**Comment by Phyks** [comment]
Ok, I missed it on my instance with only 2 persons. :/ Let's reopen this.

Not sure it can be easily monkey patched. I think it would be better to solve https://github.com/spiral-project/ihatemoney/issues/113 and https://github.com/spiral-project/ihatemoney/issues/149 together.

I can try to write something using Vue.JS, but don't want to promise anything till I am sure to have enough time to finish it.

@almet Such a new UI is expected to be built on top of the API, right?

**Comment by almet** [comment]
@Phyks we can discuss this in #149 instead. The API would be used, yes!

**Comment by almet** [comment]
It's been a while since we discussed this, apparently the issue is gone on latest firefox on my mobile. Can you confirm?

**Comment by pyg77** [comment]
Works perfectly on the demo :)
Thanks everybody!
