### ISSUE TITLE
Hide custom Datepicker on mobile

### ISSUE THREAD

**Issue by aavenel** [spiral-project/ihatemoney#221]
When adding a new bill on android phone, custom datepicker is displayed as a duplicate of the standard one.

Steps to reproduce :
Config : chrome on Android,
Add a new bill
Click on Date field -> date picker from standard android is displayed
Validate -> Custom datepicker is still visible

**Comment by aavenel** [comment]
This is also a problem on desktop : both default calendar and custom are displayed.

![virtualbox_ubuntu-gitlab_20_06_2017_21_55_37](https://user-images.githubusercontent.com/303767/27353215-93d14374-5603-11e7-87d0-d905bba97604.png)


Should we keep our custom datepicker ? Or just let the default one do the job ?

**Comment by almet** [comment]
I believe that whenever there is a custom one we should use it as it probably showcases a better UX than what we have. But, older browsers for instance don't have any UX for the datepicker, and as such we should keep ours.

There are probably other people who thought about this. I'm actually astonished that bootstrap doesn't do it by default. This is something to investigate though, thanks for reporting!

**Comment by JocelynDelalande** [comment]
20 juin 2017 22:24 "Alexis Metaireau" <notifications@github.com> a écrit:

> I believe that whenever there is a custom one we should use it as it probably showcases a better UX
> than what we have. But, older browsers for instance don't have any UX for the datepicker, and as
> such we should keep ours.

Agreed.

> There are probably other people who thought about this. I'm actually astonished that bootstrap
> doesn't do it by default. 

I am too…

> This is something to investigate though, thanks for reporting!

We are using an alpha version of BS4 ; maybe we should upgrade to see if it got fixed in stable version ? I'm saying that, but I have no time to start digging this one, anyone ?

Thanks for reporting, anyway :-)

**Comment by almet** [comment]
Anyone can tell us if it's still the case with the current bootstrap version?

**Comment by almet** [comment]
This is also happening on latest Firefox.

**Comment by JocelynDelalande** [comment]
A quick-n-dirty-but-better-than-current-state workaround would be to use `input type=text` field for date, which would disable user-agent control.
