### ISSUE TITLE
Have a «ihatemoney» command

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#228]
that would be nice to have ihatemoney runnable via a «ihatemoney» executable. This will probably lead to a few changes in how everything is currently done. For instance, I would like to have the following commands:

- «ihatemoney serve» to start the server;
- «ihatemoney init» to create a configuration file;
- Maybe we should also have a «ihatemoney migrate» in order to run the migrations, but that might be out of scope.

**Comment by almet** [comment]
I just realised that we already have this thing, in the «manage.py» file. It provides a way to run the migrations and run the server. So it's probably just a matter of packaging it under the right name.

**Comment by JocelynDelalande** [comment]
closed by #230
