### ISSUE TITLE
Use unique URIs to share projects

### ISSUE THREAD

**Issue by 0livd** [spiral-project/ihatemoney#232]
A nice enhancement would be to be able to share a project with a link of the following form https://ihatemoney.org/projects/-uuid-, just like on framadate.org. IMO it would be a much better design than the actual one where we store an unhashed password in the database (even if there is a warning). For backward compatibility, we could keep the password authentication but it would be hashed in the database.
Related to #140

edit: readability

**Comment by 0livd** [comment]
@almet @JocelynDelalande Any thoughts on this ? I might be better off submitting a WIP PR to show what I have in mind...

**Comment by almet** [comment]
Thanks for this proposition.

Why not having the ability to share a project with an unique URI, but I think that not having to remember anything that looks like an UUID is a better design. Having to remember a project name + password is something that currently works versus having to go to the emails to find the link that was used to share the project.

This would add a new feature to the existing feature set, and I would like to keep the overall number of features small (mainly because we're rather bad at UX).

Now, if we want to have this feature, we could add it to the current feature set, but I would not replace the current behaviour with it.

**Comment by 0livd** [comment]
The main idea behind this is to increase security by not storing unhashed passwords anymore. In the current design we store cleartext passwords to be able to :
- recover a lost password
- share a project by sending its credentials by email

The first one could be easily avoided by sending a token link to the user so he can reset his password via a dedicated form.
One way to avoid the second is sharing projects with an unique URI.

So yeah what I propose is not to add another feature but to replace the current behavior of the project sharing system. I am in favor of increased security even at the cost of a less convenient UX (going to the emails to find the project link).

**Comment by almet** [comment]
Hi, I'm back :-) I dont like to break features like that. It's never à good idea for the users.

Why not having this as a way to share links ! As to storing passwords in clear, we can probably just change that and hash it with a salt, which would change less the existing feature. What do you think?

Also using a link sent by e-mail to connect seems as insecure as sending the password in clear, but is less easy to remember. 

Happy to be back, lets move this forward !

**Comment by 0livd** [comment]
>Why not having this as a way to share links ! As to storing passwords in clear, we can probably just change that and hash it with a salt, which would change less the existing feature. What do you think?

The thing is that if we want to hash the passwords in the database, we have to reimplement the 2 features that need clear text passwords.
Just to be sure we understand each other correctly, what I propose is not to completely remove the current projectID/password login system. What would change for the users is only the way they share projects and recover passwords, they would still be able to log in with their projectID/password as usual. Sorry if that was not clear enough.
>Happy to be back, lets move this forward !

:)

**Comment by almet** [comment]
Ah okay, sorry I misunderstood what your proposal was (the month off might not help here :p). I think we have a consensus here: let's keep the current login mechanism and let's change the way we share links and recover passwords.

We could also lead the users to share their password via a different mean (if possible via voice !).

**Comment by 0livd** [comment]
Yeah the first post was actually not that clear.
Ok so I'll try to propose something soon :)
