### ISSUE TITLE
Basic math operations

### ISSUE THREAD

**Issue by Phyks** [spiral-project/ihatemoney#234]
Hi,

Not sure how relevant it is, but often I have a bill with multiple entries and I want to enter the sum of some entries in ihatemoney.

I usually have `bc` running in a term next to my browser to handle it, but was thinking that maybe this could be handled directly by `ihatemoney`.

**Comment by almet** [comment]
Ah, that would be Nice, I havent though about it ! Seems simple enough :-)

**Comment by JocelynDelalande** [comment]
>
> Not sure how relevant it is, but often I have a bill with multiple
> entries and I want to enter the sum of some entries in ihatemoney.

Seems nice feature.

Possible non-intrusive and safe design : handle basic operations (sum,
subsrtaction, multiplication) with JavaScript.

- the user enters its operation
- on input unblur or form submit, javascript computes the sum and
replace the operation with its result

WDYT ?

@Phypks : would you code it ?

**Comment by Phyks** [comment]
Sure, that sounds nice!

I'll try to handle it, as I need it :)

**Comment by almet** [comment]
I'm flagging this as a good first issue as I think it should be easy enough, but I might be wrong and some help might be required in order to accomplish this. If it's the case, don't hesitate to comment on this pull-request and we'll try to help you out :-)

**Comment by Phyks** [comment]
Sure, I think it's quite easy to achieve and a good first issue. I really have quite a lot of backog at the moment, so if anyone else is willing to give a try, feel free to do it :)
