### ISSUE TITLE
Better document how to download ihatemoney

### ISSUE THREAD

**Issue by 0livd** [spiral-project/ihatemoney#238]
The recommended way to get the code in the installation doc is ``git clone https://github.com/spiral-project/ihatemoney.git`` which does not correspond to the latest stable release.
We could :

- tag a release as the ```latest release``` so ihatemoney could be downloaded following this link ``https://github.com/spiral-project/ihatemoney/releases/latest``
- provide the link to pypi ``https://pypi.python.org/pypi/ihatemoney``
- create a ``stable`` branch which points to the latest release
- keep ``git clone`` and add a ``git checkout -b stable 1.x`` step (sounds complicated...)

IMO ``git clone https://github.com/spiral-project/ihatemoney.git`` should go in the contributing section

**Comment by JocelynDelalande** [comment]
> - tag a release as the ```latest release``` so ihatemoney could be downloaded following this link ``https://github.com/spiral-project/ihatemoney/releases/latest``
> - provide the link to pypi ``https://pypi.python.org/pypi/ihatemoney``
> - create a ``stable`` branch which points to the latest release
> - keep ``git clone`` and add a ``git checkout -b stable 1.x`` step (sounds complicated...)


The actual question is what is our "official" insallation method.
I'd suggest pip, which means we have to document the venv
creation (the makefile is not usable with pip method). WDYT ?

> IMO ``git clone
> https://github.com/spiral-project/ihatemoney.git`` should go in
> the contributing section

+1 (let's keep git use for development stuff)

**Comment by 0livd** [comment]
> The actual question is what is our "official" insallation method. I'd suggest pip, which means we have to document the venv creation (the makefile is not usable with pip method). WDYT ?

I'd rather go for the easiest solution: keep everything on github ...but pypi is fine too and in this case something like ``ihatemoney make-venv`` could be used for virtualenv stuffs, see #228.

**Comment by almet** [comment]
I think that using PyPI to release our software is the current de-facto standard, and as such that's what we should publicize. You want to install Ihatemoney ? Fine ! Do a `vitualenv ihm && pip install ihatemoney` and you should be good to go!

As stated in #227, I would love to see ihatemoney included in Debian for instance, so it's easier to install for our users, but I don't have any debian fu yet! Any help would be appreciated :-)

Github should be only advertised for developers and cutting-edge use (e.g. not stable). We should indeed update the documentation accordingly, thanks for noticing!

**Comment by JocelynDelalande** [comment]
Seems we didn't reached consensus yet :-)

@0livd does your opinion remain the same (preference for publicizing github) after reading @almet message ?

**Comment by 0livd** [comment]
@JocelynDelalande Let's go for pypi :)
