### ISSUE TITLE
Change the default location of the database file

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#241]
Following a discussion in #229 with @0livd and @JocelynDelalande I'm opening an issue to discuss the idea to change the default location of the database or the one used in the examples.

I personally like the idea proposed by @JocelynDelalande : let the default as it is right now and change the location used in the examples.

**Comment by 0livd** [comment]
So this would only be a suggestion, like ``/etc/ihatemoney`` for the settings ?
IMO the main issue for the moment is that when we do a ``git clone && make serve``, it doesn't work out of the box and the default database path needs to be manually changed. But there might be another way to solve this issue ?

And should we provide a way to automatically create these directories, ``/etc/ihatemoney`` and ``/var/lib/ihatemoney`` ? For the settings, the example files could be directly pasted into ``/etc/ihatemoney``. Currently ``/etc/ihatemoney`` creation is let to the user

**Comment by almet** [comment]
You are correct, we have an issue with the current setup, but I'm not sure this is related to the location of the database. I've tried to change the default location to `sqlite://` which loads a memory backend, and I still have an issue with the `project` database not being found. I'm currently investigating locally, but I would welcome any input.

Now, for the second thread of this discussion, I think we should *not* try to create the directories, it's the responsibility of the packager or the person installing the software.

In addition, it's worth noting that not all Linux distributions agree on where the data should go. As such, I believe we should try to be agnostic whenever possible.

**Comment by almet** [comment]
I'm not sure how we should make this go ahead. Any idea?

**Comment by JocelynDelalande** [comment]
Actually, since #275 the problem seems handled (IMHO):

- default is still to put it in /tmp, which seems fine for development
- production defaults (via `./manage.py generate-config ihatemoney.cfg`) put it in /var/lib/ihatemoney.

Another (maybe safer) option for « development default » might be to store the db in the path of cloned folder.

**Comment by almet** [comment]
I can't reproduce, closing.
