### ISSUE TITLE
Control public project creation via a flag when using the API.

### ISSUE THREAD

**Issue by 0livd** [spiral-project/ihatemoney#246]
Even when disabled, public project creation is still possible via the API.

**Comment by almet** [comment]
It's just a matter of adding a conditional check in the correct `ProjectHandler` that lives at https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/api.py#L32

Flagging as a good issue to get started.

**Comment by JoseAntonioTorre** [comment]
I would be interested in working on this issue.
What do you mean @almet with checking a ProjectHandler?

**Comment by almet** [comment]
@JoseAntonioTorre the correct link is now https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/api.py#L77

You just need to add a conditional here. The flag is `ALLOW_PUBLIC_PROJECT_CREATION`, and you can access its state with `current_app.config.get(flag)`.
