### ISSUE TITLE
HTTPS and Google Chrome

### ISSUE THREAD

**Issue by Pofilo** [spiral-project/ihatemoney#255]
Some requests make the application not usable in HTTPS. Is there a way to fix it ?

These days, HTTPS for web applications is a must have !

**Comment by 0livd** [comment]
Could you produce some logs/screenshots/... ?

**Comment by Pofilo** [comment]
Yeah sure !

First, in Google Chrome (but not in Firefox), the icon is grey and not green:

![ihm](https://user-images.githubusercontent.com/7527594/29242267-05537828-7f8a-11e7-9919-359644be24f3.png)

Then if I press F12, I can see that Chrome detects _Mixed-content_:

![ihm2](https://user-images.githubusercontent.com/7527594/29242268-055cca7c-7f8a-11e7-92bc-d021784a9ecc.png)

Finally, the requests which are in mixed-content are:

![ihm3](https://user-images.githubusercontent.com/7527594/29242266-05232448-7f8a-11e7-9f42-d1652083ad9a.png)

In details, it means:

![ihm4](https://user-images.githubusercontent.com/7527594/29242299-b5d6ecde-7f8a-11e7-8308-2479b7119a6f.png)

I don't really know why Chrome detects mixed-content and not Firefox ..
Of course, my version of Chrome is up-to-date.

If you have any ideas ;)

(the problem appears on [https://ihatemoney.org/](https://ihatemoney.org/) and also on my own instance on my server)

**Comment by almet** [comment]
I believe this is because the browser requests `favicon.ico` and gets redirected because the app thinks it's the name of a project. This should be easy to fix if for instance we do not accept dots in project names.

Adding this issue to the list of easy picks as it's a simple routing issue.
