### ISSUE TITLE
Hand cursor not showing up on user actions

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#260]
Those are clickable areas, a hand cursor should be presented to user, like on hyperlinks.

![image](https://user-images.githubusercontent.com/429633/29485121-cd39c2c4-84cc-11e7-939f-396cae70c077.png)

**Comment by opi** [comment]
According to some UX expert, it could be a bad idea to use the had cursor: https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

Anyway, some visual indication should tell the user that an element can be clicked (color change, underline, ...)

**Comment by almet** [comment]
Thanks for your input on this, we probably might just underline them on hover then!
