### ISSUE TITLE
pip + stable path to assets.

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#261]
We now use pip to install ihatemoney. cf #252.

This leads to an issue : pip installs the assets in a clumsy path like *$VIRTUALENV/lib/python3.5/site-packages/ihatemoney-1.1.dev0-py3.5.egg/ihatemoney/static/css/main.css*.

Which is pretty bad, because:

- it's dynamic (cannot be explained easily in doc)
- the path will change any time you upgrade to a newer version, so vhost conf will have to be upgraded on each pip upgrade.

## Solutions ?

Other pip packages like  sphinx sem to install in predictable paths, eg:

```
± find /home/jocelyn/.virtualenvs/test/ -path */sphinx/*.css 
/home/jocelyn/.virtualenvs/test/lib/python3.5/site-packages/sphinx/themes/pyramid/static/ie6.css
/home/jocelyn/.virtualenvs/test/lib/python3.5/site-packages/sphinx/themes/pyramid/static/epub.css
/home/jocelyn/.virtualenvs/test/lib/python3.5/site-packages/sphinx/themes/scrolls/static/print.css
/home/jocelyn/.virtualenvs/test/lib/python3.5/site-packages/sphinx/themes/default/static/default.css
/home/jocelyn/.virtualenvs/test/lib/python3.5/site-packages/sphinx/themes/nonav/static/nonav.css
```

**Any idea on how to do the same ?** Other ideas of solutions ?

**Comment by almet** [comment]
That's a good question! I've had a quick look at the [`setup.py` file of sphinx](https://github.com/sphinx-doc/sphinx/blob/master/setup.py) but I don't understand how they accomplish this so far.

Maybe @Natim will get an idea on how to accomplish this?

**Comment by Natim** [comment]
That's the https://github.com/sphinx-doc/sphinx/blob/master/setup.py#L217 `zip_safe=False`

**Comment by almet** [comment]
I don't understand how `zip_false` accomplishes this, either from reading the SO thread or from the [setuptools documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=zip_safe#setting-the-zip-safe-flag).

If it solves our problem, then that's great (except from my ability to read their docs, heh); but I think we need to try it before calling it solved :-)

**Comment by JocelynDelalande** [comment]
Erf, actually we already have `zip_safe=False` in [our setup.py](https://github.com/spiral-project/ihatemoney/blob/master/setup.py#L67).

**Comment by almet** [comment]
Gasp. Actually, after a quick look, I don't understand exactly what we're trying to solve here. On my computer, the files are installed in the correct way (from latest master).

e.g. in this directory: ```/home/alexis/dev/newenv/lib/python2.7/site-packages/ihatemoney/static/```. How did you do the installation?

**Comment by JocelynDelalande** [comment]
@almet actually, my ihatemoney install was with a `setup.py install`, that explains the weird paths not a pip one.

 So, that way, the paths remain stables uppon update. Seems fie. 
Also, I think the installation doc is good enough as-is for now. I close the issue.

Sorry for opening this nearly-useless discussion :x 

(Bright side : i learnt a subtle difference between pip-installing and setup.py-installing stuff).

**Comment by almet** [comment]
No worries at all, let's just say python packaging is hard to understand :-)
