### ISSUE TITLE
Release v2.0 ?

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#264]
Long time since release of 1.0.

Changes since then include:

- the python package was renamed #229 
- the wsgi path changed #240 
- the official installation method changed #252 

Those could be considered as breaking changes, as updating an existing installation blindly will break the app.

Do you agree that, following semantic versioning, next version should be 2.0 ?

**Comment by almet** [comment]
I agree with this, yes! We probably should have an upgrade documentation in place before releasing 2.0 !

**Comment by 0livd** [comment]
Let's do this ! We might want to wait for #232 though, as it will provide much better security.
I hope that v3.0 will be the switch to a single page app ... or maybe v4.0 :D

**Comment by JocelynDelalande** [comment]
> We probably should have an upgrade documentation in place before releasing 2.0 !

currently (re)working on it.

**Comment by 0livd** [comment]
I'm going to start implementing #232 (using tokens I guess). My hunt for clear text passwords will finally be over and v2.0 will be way more secure :). I'll update the upgrade guide too since it will require a database migration.

**Comment by JocelynDelalande** [comment]
@0livd not sure to understand the need for documentation, database migrations, as they are implemented in ihatemoney, are supposed to be ran automatically, and should not require any user action.

**Comment by 0livd** [comment]
@JocelynDelalande Oh yeah you're right :)

**Comment by JocelynDelalande** [comment]
Aaaaand 2.0 is out :-) 

(and our PR-queue is empty !)

Released on pypi and tagged on git.

@almet `make release` worked like a charm :-)

**Comment by almet** [comment]
Nice, thanks! I'll need to update the demo server at some point! (I fear with all these updates :p)
