### ISSUE TITLE
Fix installation doc to avoid storing db in /tmp/

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#266]
Default database location [is in /tmp](https://github.com/spiral-project/ihatemoney/blame/master/ihatemoney/default_settings.py#L11). Which is good for testing but bad for production.

We must mention the need to tweak this setting in installation documentation, as */tmp* often gets flushed on boot, this default is dangerous for production.

Has to be fixed prior to 2.0 release (#264)

**Comment by almet** [comment]
Also, we could issue a warning in the console when the default database path is /tmp, with a link to the docs :-)
