### ISSUE TITLE
Removing requirements.txt

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#273]
To avoid dependencies list duplication. Replacing [its use](https://ihatemoney.readthedocs.io/en/latest/contributing.html#the-hard-way) by 

    pip install -e .

I'm wondering if there are there any downsides doing this ?

**Comment by almet** [comment]
Yeah, that probably makes sense. I don't see why we should keep the two lists separated. My call on this is to remove it and we can add it back later if needed.

**Comment by Phyks** [comment]
Personnally, I'd rather keep the `requirements.txt` file, but load it dynamically in the `setup.py`. I tend to think this is the easier way to deal with dependencies. See for instance [this code](https://github.com/Phyks/libbmc/blob/master/setup.py#L15-L24) for an example in the `setup.py`.

**Comment by almet** [comment]
Yes! I think it's even better, let's go for it :)
