### ISSUE TITLE
Remove stderr noise from generate-config

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#277]
```
$ ihatemoney generate-config nginx.conf 
/home/jocelyn/dev/ihatemoney/ihatemoney/run.py:72: UserWarning: Running a server without changing the SECRET_KEY can lead to user impersonation. Please update your configuration file.
  UserWarning
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
server {
    server_name ihatemoney.example.com;  # CUSTOMIZE
    keepalive_timeout 5;
[…]
```

It is harmless (the first noisy lines are in stderr not stdout), but confusing. re-organising `manage.py` a little should avoid that.

ref #275

**Comment by almet** [comment]
What would you expect as the output? I tend to think that having the warning about the password is a good thing, and that we should remove the INFO, do you agree?

**Comment by JocelynDelalande** [comment]
> we should remove the INFO, do you agree?

Yes, at least INFO, if not WARNING.

So… I'm wondering… In one side polluting user display is bad, and
may be confusing (the stdout/stderr distinction does not apply to
the eyes), on the other side, warning the user is something
useful.

At the end, I think I would prefer to suppress warnings from
output also (for the generate-config command only).

User have other ways to receive the same warning (gunicorn/apache
logs, and run.py), and the config generator makes it harder to
missconfigure ihatemoney.

What do you guys think ?

(for the record, there is another warning that the one about the
password, which is the one about unchanged SECRET_KEY).)

**Comment by almet** [comment]
The thing is that most people don't look at the warnings in their logs :( I think that it's good to have this warning printed anywhere we can, as it's the only way we have to warn the user.

If they want to ditch the warning, well... they should probably fix their configuration :)

**Comment by JocelynDelalande** [comment]
Doh, I though I replied this one already :x.

> If they want to ditch the warning, well... they should probably fix their configuration :)

No, that is wrong and misleading : at the time one generate its configuration (typically, just pip-installed,  following the documentation building configuration with `generate-config ihatemoney.cfg`) command :

- they are currently using a configuration that will produce warnings (`generate-config` runtime env with default settings)
- they are, at this very time, generating configuration that will be warning-less and perfectly fine

So, that is IMHO very confusing, as we warn the users at the time they do the right thing to fix their configuration

**Comment by almet** [comment]
Thanks for pointing that out, I now understand what you mean.

It's true that these should be silenced at this installation stage: my remark from end of October doesn't make any sense in the light of what you're saying!
