### ISSUE TITLE
Use a different dependency for the REST API.

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#298]
@JocelynDelalande pointed out recently a bug that is related to a package (flask-rest) I published back in the day (6 years ago) to do the REST API.

I've published a change on the package to fix the issue, but it's interesting to note that this package is not really maintained, and doesn't have tests. I wrote this at a point where I wasn't aware of the best practices for software development, I fear.

Since that, the ecosystem had changed quite a lot and I think we should consider changing the dependency to something else (https://flask-restful.readthedocs.io/ ?)

What do you think?

**Comment by JocelynDelalande** [comment]
Seems legit :)
