### ISSUE TITLE
Add Version number ?

### ISSUE THREAD

**Issue by Pofilo** [spiral-project/ihatemoney#314]
I think we should add the version number of **ihatemoney** into the main page (and or somewhere else) in order to allow users to know which version is installed !

For example on [the hosted version](https://ihatemoney.org/), we can't easily know which version is installed.

**Comment by JocelynDelalande** [comment]
Fair enough.

**Comment by almet** [comment]
Hi, thanks for your comment.

From there, I started wondering about the security implications of displaying such a version number, and [it seems to be a best practice](https://security.stackexchange.com/questions/4940/is-displaying-what-server-i-am-running-on-the-error-pages-a-security-risk) **not to** display it.

I'm curious: what's your use case?

**Comment by 0livd** [comment]
Hi @Pofilo, IMO this would be a nice to have feature but maybe only on the admin dashboard to mitigate the security issue raised by @almet.
That's the downside of having a Changelog, people now have easy access to the vulnerabilities of a specific version :).

**Comment by Pofilo** [comment]
Ok, good reason :)
