### ISSUE TITLE
Remove sidebar on statistics view

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#323]
![image](https://user-images.githubusercontent.com/429633/35769223-30200dc0-0908-11e8-826f-1b8559e2b915.png)

It seems to me totally redundant with the central table. What do you think ?

**Comment by almet** [comment]
Yes, it is! Removing the sidebar seems the way to go here.

**Comment by Nikosmonaut** [comment]
How would you image this page. Literally removing the sidebar ?
![stats](https://user-images.githubusercontent.com/45662151/59563355-321fef00-9039-11e9-9ec6-99e80bda995c.png)

**Comment by Glandos** [comment]
The issue with this is the lack of consistency. The sidebar is indeed rendundant, but its color and size is the identity of ihatemoney.
Maybe, instead of removing it, we could increase it in this page to include those statistics.

**Comment by gustavofc** [comment]
I suggest not remove the sidebar, but the column Balance in the main page.

**Comment by jyleong** [comment]
Hello, I've decided to take this on and put up a PR. What do I have to do or who to contact to get it merged in?

**Comment by almet** [comment]
Hey @jyleong the best way to do this is to create a new PR. You don't need to assign it to anyone, and somebody will eventually come and review it :-)
