### ISSUE TITLE
Spam on hosted ihatemoney demo

### ISSUE THREAD

**Issue by aavenel** [spiral-project/ihatemoney#328]
Hi all,

I've noticed that there are some insults and low quality content on the demo project of https://ihatemoney.org/demo/

Perhaps we could try to reset each day the demo project with some example data ?

**Comment by almet** [comment]
Yes ! I've actually deleted it just right now, the best way to do this seems to be with a few requests on the API and a crontab…

**Comment by Glandos** [comment]
It seems that the demo project is clean from time to time. Can we consider this closed?
