### ISSUE TITLE
Add a new bill - Sort members alphabetically

### ISSUE THREAD

**Issue by tagru** [spiral-project/ihatemoney#333]
When a new bill is added, the members in for whom was paid are not sorted alphabetically. It looks like they are sorted by the order in which they were added (probably ID).

Can this be changed?

The member overview on the left side already does this correctly IMO.

**Comment by almet** [comment]
Yes, it's possible! Here is where you should change the code: https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/templates/forms.html#L104
