### ISSUE TITLE
Admin password: This admin password is not the right one. Docker container

### ISSUE THREAD

**Issue by dthrash** [spiral-project/ihatemoney#334]
I have modified the Dockerfile to include an admin password. I have built the project multiple times using "docker build -t ihatemoney --build-arg INSTALL_FROM_PYPI=True ."

Every time when logging in as an admin, the software says my password is wrong. Which is not the case. How can I go about troubleshooting this error in more detail?

**Comment by dthrash** [comment]
Receiving the below error message. 
After running: `docker exec -ti ihatemoney ihatemoney generate_password_hash `
After receiving a password prompt. The password was entered and a hash was returned.
I then rebuilt the docker image after adding the hash into the config. Still not working.
I noticed that if I enter the same password multiple times, a different hash is presented every time. Shouldn't output be a one way hash?

`/ihatemoney/ihatemoney/run.py:102: UserWarning: The way Ihatemoney stores your ADMIN_PASSWORD has changed. You are using an unhashed ADMIN_PASSWORD, which is not supported anymore and won't let you access your admin endpoints. Please use the command 'ihatemoney generate_password_hash' to generate a proper password HASH and copy the output to the value of ADMIN_PASSWORD in your settings file.
  UserWarning`

**Comment by almet** [comment]
I'm not using docker, but maybe @0livd or @pR0Ps can help here?

**Comment by 0livd** [comment]
Hey, just pushed a PR which fixes this. The problem is that the password hash contains a ``$`` sign which is interpreted as an inner variable by the bash interpreter. Using single quotes instead of double when writing the configuration fixes it.

> I noticed that if I enter the same password multiple times, a different hash is presented every time. Shouldn't output be a one way hash?

The password hashes are salted so it's the expected behavior :)

**Comment by theScrabi** [comment]
Little tipp: If you are writing a **docker-compose.yml** file you would want to replace the `$` in the password hash with a `$$`. This will escape the dollar sign, so it can be processed by `docker-compose`.
