### ISSUE TITLE
drop location comments in pot/po files

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#339]
Diff implying po/pot files are hard to review with git because of location comments (ex: https://github.com/spiral-project/ihatemoney/pull/338/files ) that will trigger irrelevant diffs all the time (line numbers change).

OK if we drop them ? (using `pybabel --no-location`). In the same idea, we could drop totally the po/pot header (but I see no option for that).

All those features have an interest when we do not version po/pot in git but use an external translation tool instead (but that is not what we do).

**Comment by almet** [comment]
That's okay for me! Let's keep things straightforward!
