### ISSUE TITLE
pip 10 breaks setup.py

### ISSUE THREAD

**Issue by jhass** [spiral-project/ihatemoney#340]
The `req` module is gone. My current workaround is to `pip install pip==9.03` in the virtualenv.

**Comment by JocelynDelalande** [comment]
Thanks @jhass this is pretty bad. 

https://github.com/capless/warrant/pull/101/files for a possible fix. 

Anyone to implement and test ?

**Comment by JocelynDelalande** [comment]
note that this is why current travis CI is broken on master.

**Comment by JocelynDelalande** [comment]
Fixed via #341
