### ISSUE TITLE
Problem with division and sum

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#342]
With unexact divisions, as dividing by 3 a facture of 30.50€, the sum in the sidebar is inexact.
When doing reimbursement, impossible to sold the accounts neatly.

**Comment by Nartagnan** [comment]
Perhaps generating an "extra cent" (or the opposite), the one receiving it being sorted randomly with the name of the project and the number of the user, and the number of factures.
Possible to put a star near the user holding the "extra cent" (or a black star for the one lacking a cent)

**Comment by almet** [comment]
See #165.
