### ISSUE TITLE
Settle

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#343]
No possibility to easily settle accounts.
It is the same than a bill but for only one to one. It could appear in an other color in the "Bill" tab.
Perhaps having a button at each line "account settled" to automatically create the according bill.
(In bills tab, having a different color for settle transactions and bills)
Also having an other button in the "Settle" tab : "other reimbursement" which open the same box than "create a new bill".

**Comment by almet** [comment]
See #137.
