### ISSUE TITLE
"languages" buttons not visible enough

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#344]
It is perhaps a detail, but at first I didn't saw the site was available in French.

**Comment by almet** [comment]
I believe this is a dupe of #35

**Comment by almet** [comment]
Ah, apparently not. Let's keep the discussion going. I think that if you found it afterwards it's good enough. What do you propose ?

**Comment by Nartagnan** [comment]
Flags is not good, but perhaps adding a label :
Language : EN, FR
in bold, and in MAJ for the languages perhaps ?

**Comment by almet** [comment]
I'm not a big fan about adding yet another text here that will probably clutter a bit the UI.

What about having this in the settings instead? We could:

- detect the language automatically with the browser settings (a specific HTTP headear `Accept-Language` I think is sent)
- in the settings, make it possible to change the language?

That should get us covered for 80% of the users.

**Comment by almet** [comment]
We've changed that in recent versions, it should be easier to find!
