### ISSUE TITLE
UX : error message for "project's name already taken"

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#346]
> Project identifier: The project identifier is used to log in and for the URL of the project. We tried to generate an identifier for you but a project with this identifier already exists. Please create a new identifier that you will be able to remember

The error message was in red, as for a technical problem. Perhaps having a friendlier one as it is not critical.
Also, when you try something else, if it is also used, absolutely nothing change. (if the message do not change, I just though "I didn't click, I'll try again", but it was not that)
I suggest :
> Project identifier: "ALREADY TAKEN PROJECT NAME HERE" The project identifier is used to log in and for the URL of the project. We tried to generate an identifier for you but a project with this identifier already exists. Please create a new identifier that you will be able to remember

If the message is dynamic, it will be also easier to understand what it is about.

**Comment by almet** [comment]
Nice one! I agree, let's change this :)
