### ISSUE TITLE
Bug : trying to access a deleted bill

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#349]
When you double-click to delete a transaction, you go on a 404 error.
When you go back <- the transaction seems to still be here (but it is deleted, and the page is not refreshed) and trying to delete it again => 404.

Replacing this 404 by "transaction inexistent or already deleted" could be a solution.
Filtering the double-click could be nice too.

**Comment by almet** [comment]
Nice catch for the double click! It seems an easy fix (let's catch the double click in addition to the simple click).

The 404 page actually seems normal: the bill doesn't exist anymore. Although we could improve the 404 pages as well. I've created #356 for it.

**Comment by DiegoCaraballo** [comment]
@almet @Nartagnan Hi, I wish I could help with this problem. I await your comments. Regards

**Comment by almet** [comment]
This issue is now closed, see the previous commits.
