### ISSUE TITLE
Augment the settle tab with a graphbar

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#351]
Adding a horizontal graphbar under everyone name (in transparency ?)

**Comment by almet** [comment]
This seems related to #136. It seems it would visually help to have these graphbars :-)

**Comment by almet** [comment]
I wonder what would be useful here? Should the bars show the current balance, or should they show the different values for different users, at different dates (for instance once per month?)

**Comment by almet** [comment]
Dupe #136.
