### ISSUE TITLE
Project name not visible enough

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#352]
Name of the project not really visible. Could be problematic when having more than 1 project.

**Comment by almet** [comment]
Then that seems to be a style issue. The name of the project appears on the top right. What kind of changes do you suggest to be more visible?

**Comment by Nartagnan** [comment]
I suggest, instead of :
LOGO    |    Bills / Settle / Statistics    |    Lang    |    Project's name
Having
LOGO    |    Project's name (in bold)    |    Bills / Settle / Statistics    |    Lang    |    Settings icon

Must be tested with the smartphone rendering.

**Comment by almet** [comment]
That sounds great! Let's do it !
