### ISSUE TITLE
Negative share => crash

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#354]
When trying to put a share at "-1" the site crash.

**Comment by Nartagnan** [comment]
Error 500

**Comment by Nartagnan** [comment]
Thursday it was a bug, now it is working (even if having a -1 share should not be possible)

**Comment by almet** [comment]
Actually [it's a feature](https://github.com/spiral-project/ihatemoney/commit/a1f1655f063f8f6e20ec940b9dd20d1945e5a770) ;) (Useful to say that the system reimbursed you. It's not explained anywhere because it's intended to stay around as a hack)

**Comment by Nartagnan** [comment]
Nice one ^^

**Comment by zorun** [comment]
Actually, it depends what a "share" means in the original report.

If it's the amount of a transaction that's negative, then indeed it works (although it's hard to understand what it means!)

If it's the weight of a person that's negative, then it crashes ihatemoney, probably for the same reason as #361   I tried on https://ihatemoney.org/demo/ unfortunately, it's now broken…

**Comment by almet** [comment]
I think we have a bug! Thanks for the report, we'll try to issue a fix for it. Don't hesitate to have a look if you want in the meantime :-)
