### ISSUE TITLE
"For whom?" shares not repeated

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#355]
A (x2) or (x3) etc... could be repeated in the "for whom ?" of a bill.

**Comment by almet** [comment]
Hi,

I don't understand what you want to say with this issue. Can you elaborate?

**Comment by almet** [comment]
I'm going to answer here for all the issues you've opened: thanks for taking the time to do it, it's appreciated. 

As you can see from the list of issues open in the project, we have quite a few things that could be improved, but aren't a lot of people to work on the project on a regular basis. It works well, though.

If you want to give it a spin and fix a few of the issues you've opened, don't hesitate. I'll (or someone else) be happy to review the changes, provide feedback and merge !

Cheers.

**Comment by Nartagnan** [comment]
Hello,
no problem, we did a "test party" at the contrib'atelier thursday, and somebody told me about your awesome project. I'm not a dev, so I can only test things and give my thoughts. I'm just trying to help, no bad feeling if it is not implemented.
Tell me if it is more a bother than an help.
I'll add details where needed.

**Comment by Nartagnan** [comment]
I suggest, when somebody have 2 shares, to show it in the bill :
2018-07-05 | bobby | essai2 | bobby, bob, tobby | 30.50 (7.62 each)
Could be modified in
2018-07-05 | bobby | essai2 | bobby (x2), bob, tobby | 30.50 (7.62 each)

**Comment by almet** [comment]
Ah I see ! Why not :-)

**Comment by JocelynDelalande** [comment]
Interesting. @Nartagnan thanks for all that feedback !

I however see a risk of reducing list readability (I think about cases with groups >5 people where everyone has a share > 1, eg: counting meals over a week for a group).

Not saying it is a bad Idea, just thinking about it :-)

**Comment by almet** [comment]
I'm going to close this one as I think it's the same as what's currently proposed in #335. Don't hesitate to reopen if I'm wrong.
