### ISSUE TITLE
Internal Server Error on connection

### ISSUE THREAD

**Issue by rlecellier** [spiral-project/ihatemoney#361]
Hi, 
I currently use ihatemoney to handle my loan budget. Today i add a user (THE bank) that have 0 weight.
Then i add a bill payed by someone and that should be paied back by THE bank.
-> internal server error.
-> impossible to access previous accounting.

Is it possbile to (by order of preference):
* fix it without me doing anything <3.
* get a csv export of pre-bug budget
* get access to the logs in order to propose a patch.

Thanks

**Comment by almet** [comment]
Salut Romain,

A few things:
- It seems weird to me to have someone with a weight of zero.
- If you want me to have a look at it, I'll need a way to access your project. Ideally the project name and access code.

Thanks !

**Comment by JocelynDelalande** [comment]
Hello @rlecellier 

> I currently use ihatemoney to handle my loan budget. Today i add a user (THE bank) that have 0 weight.
> Then i add a bill payed by someone and that should be paied back by THE bank.

Following IHM weights logic : if *THE bank* has a zero weight, it would never owe money to anyone.

How did you understand the zero-weight case ?

(anyway, we should not crash with Internet Server Error, that seems like a bug)

**Comment by almet** [comment]
We probably should not allow a weight of zero, and validate the inputs?

**Comment by JocelynDelalande** [comment]
Alexis Metaireau <notifications@github.com> wrote:
> We probably should not allow a weight of zero, and validate the
> inputs?

Sounds like the thing to do for now.

**Comment by almet** [comment]
It should be fixed currently on master and on the website
