### ISSUE TITLE
Intégration d'illustrations

### ISSUE THREAD

**Issue by Jojo144** [spiral-project/ihatemoney#363]
[English sum up: some illustrations, only in French for the moment, that could be integrated to explain the software]

Avec une amie nous avons réalisé quelques dessins pour faire une sorte de manuel d'utilisation en BD :
https://cloud.girole.fr/nuage/index.php/s/TsdJQWFtoj6nLyY
Est-ce que ça vous dirait qu'on les intègre à I Hate Money ?
Ce à quoi on a pensé : une boite de dialogue de bienvenue s'ouvre avec un bouton "Image suivante" et une case à cocher "Ne plus montrer au démarrage" à chaque fois qu'on se connecte à un projet. On pourrait mettre un lien (une petite image ?) sur la page d'accueil. À voir ...

Retours bienvenus. On peut encore modifier les dessins.

Si quelqu'un a envie de s'occuper de l'intégration c'est cool sinon je le ferai mais plus tard.

**Comment by Jojo144** [comment]
>     Pour la version anglaise, il faudrait probablement traduire le texte ?

Yep, traduire c'est facile par contre soit il faut réintégrer aux images de façon pas trop moche soit il faut réécrire à la main par dessus les dessins originaux, à voir ...
On sait si il y a vraiment des utilisateurs anglophones ?

>     Est-ce que vous avez des sources modifiables pour les dessins ?

J'ai ajouté les sources dans le dossier mais c'est à peut près ce que j'avais envoyé : les dessins ont été fait à la mains et scannés. J'ai juste fait quelques retouches sous Gimp.


>     Est-ce que tu as une idée d'une solution technique qui nous permettrait d'intégrer ça au site actuel ?

Pas du tout ! Je n'ai encore jamais regardé le code de IHM... Si quelqu'un veut s'en saisir c'est bienvenu sinon j'essaierai, mais ça risque de ne pas être avant ... pffiou ...

**Comment by almet** [comment]
Je sais qu'on a des utilisateurs anglophones, c'est certain, mais je n'ai pas de stats.

**Comment by almet** [comment]
J'ai commencé à intégrer les illustrations, voire #383

**Comment by Norde** [comment]
Concernant la solution pour rendre ça traduisible :

Il faudrait décomposer image et texte en deux calque différents (idéalement en .svg pour optimiser le poids et s'affranchir des problèmes de taille).

- Le fichier .svg "image" (curé du texte) est placé en arrière plan.
- Un fichier .svg "texte seul" est généré à a volé à partir de fichiers .xml (pour chaque langue).

L'inconvénient c'est qu'il faudra forcément utiliser une police spécifique pour le texte (ça ne rendra donc pas aussi bien que le dessin), police qui sera à inclure dans les .svg (normalement ça fonctionne bien avec tous les navigateurs désormais).

En gros il faut trouver une police d'écriture adaptée (et libre) et surtout redessiner les différentes illustrations avec un outil vectoriel (Inkscape par exemple) en adaptant le dessin pour le rendre utilisable avec la-dite police.

**Comment by Jojo144** [comment]
Merci de t’intéresser à la question.
Est-ce que ça le fait si plutôt de fournir un calque texte je fourni un calque image pour chaque langue ?
Fr + en c'est bien ça ?
Auquel cas je peux faire ça dans les jours/semaines à venir si quelqu'un veut se pencher sur la PR ...
(Malheureusement je remet mon apprentissage de Flask à plus tard.)

**Comment by almet** [comment]
Salut @Jojo144, depuis peu on supporte aussi l'allemand. Si tu as une solution ou les textes sont intégrés à partir de vrais textes, c'est mieux. Si ce n'est pas possible, on peut toujours avoir une liste de langues pour lesquelles le tuto est présenté, et faire l'intégration manuellement.

**Comment by Norde** [comment]
@Jojo144 Disons que la solution avec génération de .svg à partir de xml à la volé est très souple pour la traduction (il suffit de traduire un fichier xml modèle et on à toutes les langues).

Par contre c'est vrai que ça demande un sacré boulot de mise en place (personnellement je n'ai jamais utilisé ça, mais je sait que l'utilisation de polices exotique peut être parfois délicate).

Si tu as une police qui pourrait convenir je veux bien faire des essais :)
Et si ça fonctionne bien, je pourrais vectoriser les dessins.
