### ISSUE TITLE
hosted version down

### ISSUE THREAD

**Issue by VSCHULTE** [spiral-project/ihatemoney#400]
i had 3 acounts there and the last export is really old.
will it be back online? do you have any backup?

**Comment by almet** [comment]
Hi,

The server I've been using to host ihatemoney.org is unfortunately dead, and the data with it is also gone. I was doing backups but they stopped syncing without me noticing so there is no way to get the data back.

So, ihatemoney.org website will be back but without its data. It will happen when I'll get some time to do it, probably during the next week.

**Comment by almet** [comment]
The hosted version is now back online, but without its data. A proper backup strategy is now used so tihs won't happen again.
If you're interested, you can also subscribe to the mailing list to get updates about new features / problems if they arise.

It's at https://mailman.alwaysdata.com/postorius/lists/info.ihatemoney.org/

Cheers
