### ISSUE TITLE
ihatemoney.org down

### ISSUE THREAD

**Issue by Eole211** [spiral-project/ihatemoney#401]
https://ihatemoney.org seems unreachable for more than 10 days..
Does anybody know anything about that ?

**Comment by Glandos** [comment]
See #400

**Comment by almet** [comment]
Sorry about that, the data won't come back. It will eventually be back online, when I get the chance.

**Comment by Eole211** [comment]
thank you for your answer. Sad for the data :-s

**Comment by almet** [comment]
The hosted version is now back online, but without its data. A proper backup strategy is now used so tihs won't happen again.
If you're interested, you can also subscribe to the mailing list to get updates about new features / problems if they arise. It's at https://mailman.alwaysdata.com/postorius/lists/info.ihatemoney.org/

Cheers
