### ISSUE TITLE
Expose invitation link creation via the API

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#412]
Is it possible to get an invitation link for a project using the API?
Can we make it possible ?

**Comment by almet** [comment]
I think that currently it's not possible. But it shouldn't be too complicated to do via the API!

**Comment by almet** [comment]
This means different things:
1. Create an endpoint which can generate a new auth token
2. Accept a new authentication scheme, with the auth token

**Comment by Natim** [comment]
As a first step, we could also generate a base64 basic token with an embedded payload containing the user/password in the basic format.

**Comment by almet** [comment]
It's now possible to authenticate with a token to the API, I believe what's missing is the way to create this token from the API, and this should be pretty easy to do.

**Comment by JoseAntonioTorre** [comment]
I want to help here! Could I?

**Comment by almet** [comment]
Sure thing!

**Comment by JoseAntonioTorre** [comment]
I am trying to understand which is the problem that this issue tries to solve.
I have been reading related issues and I notice that there is a share link that can be used to access to a project. Which is the use case that we are trying to support?

**Comment by almet** [comment]
Currently, you can send a share link to other people so they can login to the project without knowing its password.

This mechanism is currently onluy supported trough the web interface, and not trough the API. This issue aims at supporting this mechanism: generating the invitation link, and then using it to authenticate on the API.

Hope it's clearer, let me know if not.

**Comment by indatwood** [comment]
This was fixed with #504
