### ISSUE TITLE
Add a way to flag a bill as a reimbursement so it is not counted in the stats

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#414]

**Comment by almet** [comment]
I'm not sure to get it, can you explain a bit more?

**Comment by Natim** [comment]
Yes that's actually related to https://github.com/spiral-project/ihatemoney/issues/137#issuecomment-543591682

The stats page is supposed to give feedback on how much money each participant spent. Regardless of who paid for it.

Today when using reimbursement by hand, we add a bill saying that X paid what they owed to Y. However it breaks the stats page because it adds the reimbursement to the total.

**Comment by almet** [comment]
Okay, closing as a dupe, then, thanks!
