### ISSUE TITLE
Add a way to import previously exported json data

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#417]

**Comment by jeffspurlock** [comment]
Hello almet, I'm looking to contribute to my first open source project. It looks like you need something that can parse through the json data from a previous export... is that data that was exported from ihatemoney, or is this json data coming from elsewhere?

**Comment by almet** [comment]
Hi @jeffspurlock, nice that you chosen our project to contribute :-)

It's only data exported from ihatemoney :-)

**Comment by NVanvyve** [comment]
Hi, I'm also interested in this problem.
I looked at the project a little bit and wondered where to integrate the import of json.
Do we want to import the data and create a new project, do we add it to an existing but empty project, or do we import the json and add the data to a project that already contains " bills "?
Basically if I have to create an "import" button, do I have to do it on the homepage or in the project's option menu? :)

**Comment by almet** [comment]
The simplest of all of them: import to an existing project, that should be enough to get started.

**Comment by waqarmuhammad1** [comment]
Hi, if this issue still open i would like to contribute in it.

**Comment by almet** [comment]
@jeffspurlock @waqarmuhammad1 @NVanvyve one of you will need to take it over, I suggest @jeffspurlock does it, if that's okay for you, as you were the first one to propose. What do you think?

**Comment by almet** [comment]
Haha, so in the end, anybody wants to work on this?

**Comment by NVanvyve** [comment]
I'm still ready to work on it, but I thought @jeffspurlock had priority. If nothing moves, I start working

**Comment by almet** [comment]
Awesome, don't hesitate to go for it :-)

**Comment by NVanvyve** [comment]
It took me a little while to finally succeed in importing a JSON and identifying the data to be imported.
I extract the members who are not yet in the project, as well as their weight, I also have a list of the bills that are not in the project.
Now I just have to add his information to the database and that's where I'm blocking it. Is there a proper way to write data to it?
I'm not sure how to use (or create a variant of) the add_member function (web.py) or use the Person class

**Comment by almet** [comment]
That should be quite easy to do with the models directly, so the `Person` class. Something like :

```
from ihatemoney.models import Person, db, Project, Bill
Person(name="Noé", project=g.project, weight=1)

# Do the same for bills, etc, and then save everything with : 
db.session.commit()
```

Hope that helps !

**Comment by NVanvyve** [comment]
It works great for adding Person but impossible to add bills...
I may miss something but I don't see and I've been going around in circles for hours

```python
bill = Bill(
    what="TestBill",
    amount=12,
    date="2019-12-04",
    payer_id=9,
    owers=[7,8,9],
    id=7
)
# db.session.add(bill)
db.session.commit()
```
(id's are consistent with the context)

**Comment by almet** [comment]
hey, are you willing to push your code somewhere so we can have a look and help you out? Thanks!

**Comment by NVanvyve** [comment]
Sure
I have pushed what is functional on my fork, I also just pushed the part that doesn't work yet.
You can see the code [here](https://github.com/NVanvyve/ihatemoney/blob/master/ihatemoney/web.py#L445)

**Comment by LeoMouyna** [comment]
I toke a look at your code.
For now when we want to save a Bill we do those steps:

1. Generate a form
2. Generate a bill
3. Send the form with the bill by using 
```
db.session.add(form.save(bill, g.project))
db.session.commit()
```
You are manipulating Bill directly and I don't know if you can save a Bill like you do with a Person :disappointed: 
So what if you generate a fake form with `form = get_billform_for(g.project)` and then use `session.add` followed by `session.commit` ?

Is that clear enough ?

**Comment by NVanvyve** [comment]
I followed your advice. I created a form this way:

``` python
bill = Bill()
form = get_billform_for(g.project)
form.what = u"Test Bill"
form.amount=u"10"
form.date=datetime(2019,12,15,0,0,0)
form.payer=u"1" # Name of user
form.payed_for=[16,17] # List of user's id

db.session.add(form.fake_form(bill,g.project))
db.session.commit()
```
`fake_form(_,_)` is a copy of `save(_,_)` that allows me not to go via form fields
``` python
def fake_form(self, bill, project):
    bill.payer_id = self.payer
    bill.amount = self.amount
    bill.what = self.what
    bill.external_link = u""
    bill.date = self.date
    bill.owers = [Person.query.get(ower, project) for ower in self.payed_for]

    return bill
```

And I now have a reaction when I commit.
But it is only partially the one that is expected. 
After import, only the accounts of those who have debts are modified, not the one of the one who paid (in my case the user who pays is not one of the owers). This is a problem since I have two people with an account at -5€ and the rest at 0€, there is an inconstancy.
And the bill is not displayed in the list either.

I wonder what is changing in Person and Bill's models that makes their behaviour so different.

**Comment by NVanvyve** [comment]
Perfect it works!!
