### ISSUE TITLE
Items don't seem to be ordered by date

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#418]
Bills doesn't seem to be listed by date!

**Comment by zorun** [comment]
Do you have a screenshot of the issue?

It's probably caused by 0428cf06b50203432cb39bde95e450a481392797 (@Phyks ): bills are now ordered by creation date first. Maybe the ordering is messed up when the creation date is NULL for some bills?

**Comment by almet** [comment]
Here is the screenshot.

![capture du 2019-02-11 14-15-12](https://user-images.githubusercontent.com/67073/52565618-a0447300-2e07-11e9-9dbf-56ab1f2991f8.png)
