### ISSUE TITLE
Drop support for Python < 3.6 and use f-strings

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#421]
![image](https://user-images.githubusercontent.com/229453/53079468-c26c7e00-34f6-11e9-8acd-7b31081c24f4.png)

**Comment by zorun** [comment]
Debian stretch comes with python 3.5, so dropping support for it does not look like a great idea…

**Comment by Glandos** [comment]
Indeed, but Buster will be delivered with 3.7.

Will a backport be in Stretch?

**Comment by zorun** [comment]
I doubt very much that python 3.7 will be backported to stretch.  I expect that lots of servers will continue to use stretch for some years to come: it will receive security support from the Debian team until 2020, and then it will get LTS support until June 2022: https://wiki.debian.org/LTS

So, unless there is a very good reason to drop support for Python 3.5, please avoid doing this!  F-strings look like a nice feature but it's mostly code cosmetics, everything you can do with it can also be done with the "old-style" string formatting syntax.

**Comment by Natim** [comment]
Thank you for your insights on this, I am closing for now.

**Comment by Glandos** [comment]
@zorun You're right on a lot of aspect, and I agree that supporting 3.5 is a good idea.
But f-strings are not __only__ cosmetic: https://cito.github.io/blog/f-strings/
