### ISSUE TITLE
default server URL in MoneyBuster Android client

### ISSUE THREAD

**Issue by eneiluj** [spiral-project/ihatemoney#422]
Hi there,

MoneyBuster is an Android app which is compatible with IHateMoney API. It just got accepted in F-Droid today and I realize the default server URL for "IHateMoney" projects is "https://ihatemoney.org". Are you ok with that? I can change it in next release.

**Comment by almet** [comment]
Hi, glad to hear there's such an app coming along :-)

I'm pretty okay with it using the demo server, as long as the users don't think this server will be available 100% of the time. I don't guarentee any uptime on this server (even though I believe it just works most of the time).

**Comment by eneiluj** [comment]
I'm glad you're glad :wink:.

It could be useful to say talk about the uptime on the main page of the instance.

**Comment by almet** [comment]
Yep! Don't hesitate to send a PR in order to have the app listed somewhere in the interface. That would be helpful to a lot of users I'm sure!

**Comment by almet** [comment]
Oh, @eneiluj, don't hesitate to mention this on the mailing list, if you want! Links are on the README page.
