### ISSUE TITLE
Strange mail subject formatting

### ISSUE THREAD

**Issue by opi** [spiral-project/ihatemoney#427]
I created 2 different projects recently and noticed a strange formatting in mail subject (in french) : 

- `Vous venez de créer« foo bar »pour partager vos dépenses`
-  `Vous venez de créer« foo  bar » p  our partager vos dépenses`

What's wrong:

- No space before and after french quotation marks.
- In the 2nd example, an extra space was introduced in the project title (2 spaces between words).
- In the 2nd example, an extra space was introduced in the word "pour".

Original string translation: https://github.com/spiral-project/ihatemoney/blob/1cc69e22c04c252d11c0946e80f845037720dd3a/ihatemoney/translations/fr/LC_MESSAGES/messages.po#L158-L159

Message is formatted and sent here: https://github.com/spiral-project/ihatemoney/blob/24e0d8348fb5855d0255b41ec1ca9beaf233d9a6/ihatemoney/web.py#L243

**Comment by almet** [comment]
Thanks for taking the time to report the issue here. Sorry for not answering earlier :-)

I'm currently trying to understand what's going on here, definitely something weird : the translation strings seem to be correct in the codebase, but somehow they get modified.

**Comment by almet** [comment]
So, this seems to not be the case anymore locally, at least when debugging the flask_mail app. Closing for now. The deployed version is still impacted, until I update it to the latest release.
