### ISSUE TITLE
Allow to attach files (as proof of expense)

### ISSUE THREAD

**Issue by Norde** [spiral-project/ihatemoney#429]
Could the possibility of attaching a file to an expense (like proof / invoice) be feasible?

**Comment by almet** [comment]
It's technically feasible, but I don't think this is the scope we want for this software. What's your usecase here?

**Comment by Norde** [comment]
Just being able to attach proof to an expense (especially for large expenses).

It's very convenient for roommate (anyone can therefore check the accounts and trust reign).
It also makes rent receipts easily accessible to everyone.

I think it's a logical function for shared budget management software but it may not be the desired goal.
You may prefer to keep an application as simple / light as possible?

**Comment by almet** [comment]
Yep, one of the goals of IHM is to stay as simple as possible. Handling these pieces also means that the server contains a lot more valuable data than before. I'm +0 on this one. If anyone else thinks this is needed, don't hesitate to comment here :-)

**Comment by 0livd** [comment]
I agree with @almet. Another idea might be to add a new `External link` icon in the `Actions` menu, which can link to whatever this bill is related to, e.g. a file stored on nextcloud/dropbox. What do you think ?

**Comment by almet** [comment]
If that solves the problem for @Norde, why not!

**Comment by Norde** [comment]
This would be a very good solution that would not weigh down HMI!

**Comment by almet** [comment]
@Norde are you willing to work on this?

**Comment by Norde** [comment]
My knowledge of python is nil but I will take a look :)

I think that the opening of a simple field "url" is within my capabilities.
For integration with nextcloud I make no promises.
