### ISSUE TITLE
The Settle algorithm can run 100% CPU for hours if it needs to settle for less than 0.01€

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#431]
I rewrote it for elm-ihatemoney here: https://github.com/spiral-project/elm-ihatemoney/commit/19ef3fdcd227354b24e176093a2d27474d94dc86#diff-57e1d8221f5ab91dcf91dab223f5db7bR53
We should backport it to the Python version.

**Comment by almet** [comment]
Should be solved with the latest update, IHM now uses the debts library.
