### ISSUE TITLE
Add the ability to use the solver via the API

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#433]
The logic behind the resolution algorithm could be useful to other projects, as such it might be a good idea to make it available behind an API.

**Comment by almet** [comment]
finally I did this https://framagit.org/almet/debts

**Comment by charlie45000** [comment]
Wouldn't it be better to just add a settle_bills function to to the api?
Since the application already has the ability to do that, there is no use to use an external program. (or at least what are the reasons to do so?

**Comment by Glandos** [comment]
Do you have a use case to use `ihatemoney` to settle bills outside of the current user interface?

Of course this could be exposed, but `debts` is already there. It is an external program, but for me, using an API or an external program is nearly the same: you need some programming language to make the calls, gather data, etc.
