### ISSUE TITLE
User shouldn't be able to add negative bills

### ISSUE THREAD

**Issue by arnaudbos** [spiral-project/ihatemoney#45]
One of my co-workers noticed that there was no validation preventing negative bills.

Yes, it's a silly idea to insert a negative bill but still, do we ignore it and let the user do what he wants, or do we prevent wrong behaviors like this one?

**Comment by fredericsureau** [comment]
I'm such a silly user! I want to add a negative bill to represent money I've stolen from the virtual wallet.
Currently, you can only represent money people owe you.
Negative values is one (simple) way to represent money you owes other people.

**Comment by fredericsureau** [comment]
Corresponding pull request #150

**Comment by JocelynDelalande** [comment]
@almet please close as #150 is merged :-)
