### ISSUE TITLE
Password recovery doesn't display any validation message

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#455]

**Comment by LeoMouyna** [comment]
Can you please describe a bit this issue ? Which page is involved ? What are your user actions ? And what is the expected behavior ?  
Thanks :)

**Comment by almet** [comment]
Hi, when you reset a password, a mail is sent, but no validation message is shown to the user. When I did it last time, I clicked multiple times, and… received multiple emails ! So everything seems to be working, *but* no message is shown to the user when the mail is sent.

**Comment by LeoMouyna** [comment]
Seems like I got a message on ihatemoney.org.
![validationMessage](https://user-images.githubusercontent.com/17725363/64620089-8857c080-d3e3-11e9-9203-dbad1cd81a4a.png)

**Comment by almet** [comment]
Thanks for taking the time to look into this. Strange! Maybe this version of IHM fixes it, it was definitely the case with the previous release.

That being said, I believe the UX here could be better : rather than having a "flash message", we could redirect the user to another page where they're displayed a text "A link to reset your password has been sent to you, please check your emails", and it's not possible to click again on the "submit" button.

Do you want to work on this?

**Comment by LeoMouyna** [comment]
Why not, but not sure if I will be able to start it before Thursday. So feel free to do it if you want it sooner :smile:

**Comment by almet** [comment]
Oh, Thursday seems perfect. We don't have any need to rush. If you want to do it, please do it with your own agenda! :-)
