### ISSUE TITLE
Style broken when updating to 4.1

### ISSUE THREAD

**Issue by Shaac** [spiral-project/ihatemoney#463]
Hello,

I just upgraded from version 4.0 to 4.1 (using pip, and then restarting apache), and now my webpage is broken. I’m not sure what the error is, but there seems to be css issues.

In the console there is this error message `Bootstrap's tooltips require Popper.js`.

You can see my hosted version here: https://money.shaac.me/

**Comment by almet** [comment]
Hi, thanks for the report! It seems to be a packaging issue, I'm not sure yet how to fix it. Are you willing to investigate here?

**Comment by almet** [comment]
You seem to have an old version of the templates served. How is your apache configured? If you're using gunicorn, did you restarted it?

**Comment by Shaac** [comment]
Thanks for your responses. I’m using a simple apache vhost server with the following configuration

```
<VirtualHost *:443>
    ServerName money.shaac.me
    ErrorLog /var/log/httpd/ihatemoney_error_log
    CustomLog /var/log/httpd/ihatemoney_access_log common

    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/money.shaac.me/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/money.shaac.me/privkey.pem

    ProxyPass / http://localhost:5000/
    ProxyPassReverse / http://localhost:5000/
</VirtualHost>
```

I did restart apache.

To answer you’re question, I’m willing to investigate here, but I don’t want to waste your time if this is something I messed up myself.

**Comment by almet** [comment]
No worries.

It seems that the server running IHM is still running, and need a restart. It's different from apache, and from your configuration, it seems to be running on port 5000.

What's running on port 5000 ? and how ? You need to kill it and restart it and everything should be fixed, if I'm not mistaken :-)

**Comment by Shaac** [comment]
Oh yes of course. I had a different systemctl running IHM… Stupid me. I restarted it and now it works perfectly. Thanks a lot!
