### ISSUE TITLE
Commands do not yield any output 

### ISSUE THREAD

**Issue by Thaega** [spiral-project/ihatemoney#466]
As I understand it, commands such as `ihatemoney generate-config nginx.conf` or `ihatemoney generate_password_hash` should output respectively a nginx conf file or a password hash to stdout. However, running them does not yield anything for me.

**Comment by almet** [comment]
Thanks for taking the time to report this here. It's appreciated. I'm not able to reproduce this issue here (on a venv using python 3.7.3). Can you please tell me which environment you're using? thanks.

**Comment by Thaega** [comment]
I'm using Debian Buster with python 3.7.3, and I have installed ihatemoney with pip as told in the doc.

**Comment by Thaega** [comment]
After further investigation, it seems that the commands yield output if they are invoked before running `ihatemoney generate-config ihatemoney.cfg > /etc/ihatemoney/ihatemoney.cfg`. I also noticed that the file `/var/lib/ihatemoney/ihatemoney.sqlite` to which the default `ihatemoney.cfg` generated points does not exist, but I don't know if it's supposed to or if it has anything to do with my issue.

**Comment by almet** [comment]
Thanks for the additional input. That helps. I believe that something might get parsed incorrectly and silently fails. Can you please paste the content of your `ihatemoney.cfg` file here so I can investigate further?

**Comment by Thaega** [comment]
Here it is:
```# You can find more information about what these settings mean in the
# documentation, available online at
# http://ihatemoney.readthedocs.io/en/latest/installation.html#configuration

# Turn this on if you want to have more output on what's happening under the
# hood. DO NOT TURN IT ON IN PRODUCTION.
DEBUG = False

# The database URI, reprensenting the type of database and how to connect to it.
# Enter an absolute path here.
SQLALCHEMY_DATABASE_URI = 'sqlite:///var/lib/ihatemoney/ihatemoney.sqlite'
SQLACHEMY_ECHO = DEBUG

# Will likely become the default value in flask-sqlalchemy >=3 ; could be removed
# then:
SQLALCHEMY_TRACK_MODIFICATIONS = False

# This secret key is random and auto-generated, it protects cookies and user sessions
SECRET_KEY = "redacted"

# A python tuple describing the name and email adress of the sender of the mails.
MAIL_DEFAULT_SENDER = ("Budget manager", "budget@notmyidea.org") # CUSTOMIZE

# If set to True, a demonstration project will be activated.
ACTIVATE_DEMO_PROJECT = True

# If not empty, the specified password must be entered to create new projects.
# DO NOT enter the password in cleartext. Generate a password hash with
# "ihatemoney generate_password_hash" instead.
ADMIN_PASSWORD = ""

# If set to True (default value) anyone can create a new project.
ALLOW_PUBLIC_PROJECT_CREATION = True

# If set to True, an administration dashboard is available.
ACTIVATE_ADMIN_DASHBOARD = False
```

Thank you for your help.

**Comment by almet** [comment]
See #490.
