### ISSUE TITLE
Should we drop support for python 2.X ?

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#475]
Hi,

I'm wondering if we should drop support for python2.X series, and eventually modernize a bit the codebase accordingly.

What do you think?

**Comment by Glandos** [comment]
Since every major distribution have Python 3 in them (CentOS 8 is out!), Python 2 can be safely dropped.

To me, the minimal version should 3.5, but 3.6 is nice with f-strings.

**Comment by almet** [comment]
I believe having 3.6 (or even 3.7 ?) as a target would be sane. IHM is not packaged yet on any distribution, so I believe it would be okay to ask people who want to install IHM to deploy a recent version of python? (not sure, but that's a wild guess)

**Comment by zorun** [comment]
Dropping support for python2 is a good idea!

Regarding python3, this was discussed in #421, and I still believe that compatibility with python 3.5 is important.
The end-of-life for python 3.5 is still one year away (2020-09-13): https://devguide.python.org/
Same thing for Debian stretch, it is still supported until 2020 at least.
