### ISSUE TITLE
Import QIF files

### ISSUE THREAD

**Issue by RaitoBezarius** [spiral-project/ihatemoney#513]
QIF is a common format file for financial data (used by GnuCash and other software), I have some scripts which already do some conversions from CSV (what my bank provides me) to QIF and I'd like to import them in this tool in order to perform more advanced tasks with them.

Do you think it's feasible? I can add the feature myself, I just need to understand what is recommended to do (in terms of code structure, quality, etc.) and I can send a PR.

**Comment by almet** [comment]
Hi, thanks for opening an issue here. QIF seems rather old and has known limitations. Should we support OFX instead?

Also, I wonder what's your use case here, could you please elaborate, and maybe give me an exemple QIF or OFX file so that I can check that out? Thanks!

**Comment by RaitoBezarius** [comment]
I think it's okay to support QIF, it avoids users to convert QIF to XXX ; my use-case is this one:

(1) My banks provide me with CSV/QIF/OFX
(2) I process them into my personal tools, filter them, etc.
(3) And I get files which are results from shared expenses, the problem is that obviously QIF/OFX do not have user information so once those are imported, I have to add it myself maybe.

I guess it's not a super good idea then to support this feature, but I wonder how can I could get my pipeline working.

I'd like to add automatically shared expenses from personal scripts in some projects (API?).

**Comment by almet** [comment]
Okay, I'm closing the issue then, thanks :-)

About your problematic : using the API seems a good way to do this, yes!
