### ISSUE TITLE
Make weights more discoverable.

### ISSUE THREAD

**Issue by RaitoBezarius** [spiral-project/ihatemoney#514]
When I have three friends and we're managing a project where I pay for N €
And my two friends owe me M_1 and M_2 € such that M_1 + M_2 = N.

Currently, it's set so that M_1 = M_2 = N/2.

But we could enable some way to specify the owed amount, this friend owe me this part and this other friend owe me this part.

Is that easily feasible in the engine? Could I start working on a PR for that?

**Comment by almet** [comment]
Hi, there is already a mechanism for "weights", meaning that some people can have different weights in the project. Is that what you want here?

**Comment by RaitoBezarius** [comment]
Yes, exactly ; I didn't see it in the web app, is this documented somewhere?
Thanks.

**Comment by almet** [comment]
You need to click on "edit" on the members. It's currently not documented, so it's hard to discover by yourself, I agree.

**Comment by RaitoBezarius** [comment]
But, in this case, it's propagated to the whole project?
My use-case is sometimes I handle the payment for friends and I want to say that friend A owe me X and friend B owe my Y and I paid X+Y+Z where Z is only my part.

Using weights will enforce this for all expenses :/
Thanks.

**Comment by almet** [comment]
If I understand what you mean properly, I belive this can be solved by adding multiple bills, right? It means that you landed your friends some money.

**Comment by RaitoBezarius** [comment]
I wonder, let's look at this scenario:

Me, my friend A and my friend B were in the restaurant, for simplicity, I paid the restaurant for 100 €
My part was 20 €, my friend A was 30 € and my friend B was 50 €.
What's the proper way to add it?
Should I just add 3 bills of 20,30,50 ?
Or is there a way to add 1 bill of 100 and specify amount owed by each person (?).

**Comment by almet** [comment]
So, it's possible right now : you need to add the bills for your two friends : 30 and 50, in two different bills, marking you as the "payer" and each of them individually in the "for" field.

If we were to add this as only one bill in the UX, one way I can think of would be this : 

- Next to each "for" person, one an specify an amount;
- The sum of all the amount specified in the "for" in displayed in the "amount" field
- When saving these in the database, we could create two bills.

But I'm not sure it's worth the implementation effort ;-)

**Comment by RaitoBezarius** [comment]
Alright, I understand ; I agree this is better to keep it as-is, this way it'll work.
I'm just wondering the ramifications in terms of statistics, etc.

**Comment by almet** [comment]
Okay, I'm closing the issue then, thanks :-)
