### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#517]
Hi folks,

8 years ago, [I published the first version of ihatemoney](https://blog.notmyidea.org/how-are-you-handling-your-shared-expenses.html).

I'm happy with what we have done with this project : it's still straight to the point, not doing a lot of fancy cool stuff nobody needs, it's just doing a set of simple tasks, and it's doing them well.

Since its inception, we've had 10 releases (current version is 4.1.3 at the time of writing), and contributions from 39 persons, according to the git log.

I recently changed my professional career ([I'm a brewer now](https://www.vieuxsinge.com/)!), and I don't want to spend time on maintaining software projects anymore. Not that it's a pain to do, or anything like it, it's actually quite some fun, but I just don't want to take this even so small amount of time, these days.

So, while I have no problem shutting things down, it would be phenomenal to have a set of people to take this over. The amount of maintaining-work is small : a few pull requests here and there, some reviews and some releasing work, it honnestly doesn't take too much time.

I really hope people will step-up, but if it doesn't happen I will archive the project. I'll wait until the end of January 2020 to decide.

So, if you're interested, please, let me know!

Cheers,
Alex

**Comment by Natim** [comment]
Don't archive it for sure I will be willing to make release and deploy new version to alwaysdata.

As you said there isn't much to do these days appart from using it and keeping it alive.

**Comment by Glandos** [comment]
Is there any free beer for a new free software maintainer? ;)

Anyway, don't archive this. I can't be very active, but I'd like to be a co-maintainer if it is needed.

`ihatemoney` is a small-but-good project, and given the recent activity, it seems that it should keep on being as it is.

**Comment by LeoMouyna** [comment]
Hi @almet !

I hope you will enjoy your new job and I wish you good luck for your adventure ! Thanks a lot for this project it was one of my first to contribute. 

It's probably due to it small and simple architecture so I really hope it won't die with your departure ! :smile:

**Comment by MagicFab** [comment]
May I suggest changing the licence to GPLv3 ?
This will most certainly attract more possible maintainers and contributors.

**Comment by indrora** [comment]
@MagicFab It's under a perfectly fine license, no need to slather the GPL on it. 

@almet Is there a published roadmap? What work needs to be done to keep the project moving?

**Comment by douglasg14b** [comment]
@indrora 

A bit hostile no? LGPL > GPL IMHO if you are still looking for some protections. A more recognizable license that's friendly to developers isn't necessarily a bad thing, especially when looking for contributors/maintainers.

**Comment by indrora** [comment]
The license is a perfectly recognizable 3clause BSD with a silly "you should totally buy someone who's worked on this a beer some day if you meet them" addition. 

In on-topic notes, let's add this to https://github.com/pickhardt/maintainers-wanted

**Comment by Natim** [comment]
I added the PR on maintainers-wanted and I added you in a group so that you can help triage the project and start a roadmap if you want to.

**Comment by MagicFab** [comment]
@indrora I for one won't contribute specially when getting such an answer. Good luck, then.

**Comment by JJKW1984** [comment]
@MagicFab you have to grow some thicker skin man. She is just being forthright and forward in her responses. That makes for a good team if you ask me.

**Comment by Glandos** [comment]
@MagicFab You are free to avoid contribution based on your disapproval of the current license.

However, even if the answer of @indrora sounds rude to you, keep in mind that:
- She is as linked to this project as you
- The goal was asking for maintainers, not a license change.

Of course, a license change can be debated, but may be another issue for that would be the right place.

**Comment by MagicFab** [comment]
I'd love to hear from [actual contributors](https://github.com/spiral-project/ihatemoney/graphs/contributors) like @Natim @almet @JocelynDelalande @aavenel @0livd @arnaudbos @glandos @JoseAntonioTorre @eMerzh @feth @fredericsureau @Vistaus @QuentinRoy @comradekingu among others.

**Comment by Natim** [comment]
@MagicFab to be honest, I could see why a GPLv3 would be a good fit for this project.
It is not a lib so it wouldn't prevent businesses to use it.

However why do you think BSD wouldn't be a good fit?

**Comment by feth** [comment]
Sorry, I don't care about the license as long as it's free and everyone else is happy ; it's a smallish (still, useful!) project.
How about opening another issue regarding the license if this topic is important?

**Comment by arnaudbos** [comment]
I, for one, don't know what a licence change would imply, so my first reaction would be "why bother?" and I'd apply the YAGNI principle.

But again I have no particular knowledge on the matter so feel free to expose arguments and counter-arguments to try and convince me, but:  
* calm down;
* leave people out of it;
* stick to the facts;
* and please do this in another issue, this one's not meant for it.

I'm not active on this project but happy to see it's still of use and that people have stepped up to keep it going. Happy coding :-)

**Comment by MagicFab** [comment]
@Natim I care about sharing improvements. BSD licences don't require availability of source code. As such it becomes possible to improve on it and publish as proprietary binaries and distributing closed source versions which deny all users of Free software freedoms. Feel free to open a new issue and discuss this if it's important for this project. I merely asked as I looked first at the LICENCE file, not the actual README. It's now clear to me, so thanks everyone for your answers.

**Comment by comradekingu** [comment]
@MagicFab Don't think my opinion is more valuable by having contributed, @almet I am however down to try and "maintain" things, and not just kicking the wheels. My idea of that being to steer things in the direction of usability. Translations, design, GDPR info, and language mostly. As mentioned, most everything is "done", but then to me, how much of that can be improved upon for no extra bloat, or logical expanse of effort?

Licensing and communicating it is important to me, if the user doesn't know, then the experience is sold short of what it actually is, and should be, and appears to be in the ranks of many a project I don't want anything to do with. The impetus here being on the prevalence seeing precisely data regarding who buys what and when stolen, and maybe even expecting it.

Against perhaps my better judgement, I made an issue of licensing at #519

**Comment by almet** [comment]
Hi folks, I have hidden the license-related discussions, because this is not what this issue is made for. I'm not advocating against a license change, it's just that it's not the point of this issue here.

Please use #519 to discuss the matter.

**Comment by aavenel** [comment]
Hi @almet,

Ihatemoney was my first open source project as a contributor. 
The friendly comments, simple architecture and advice to keep thing simple were always appreciated. I wish every open source contributor could start with a project with such a cool community and maintainer.

I don't develop in python anymore, so I am not a right fit for the maintainer job. However, I strongly hope that someone would take over, as it is still a fun and useful project.

Alexandre

**Comment by comradekingu** [comment]
I am on https://hosted.weblate.org/user/kingu/ on Hosted Weblate, hoping to be added as admin via https://hosted.weblate.org/access/i-hate-money/ (and then I can deal with adding other project maintainers).

**Comment by almet** [comment]
So far I an see the folliwing people who proposed to maintain / co-maintain : 

- @comradekingu, but that's not clear to me on which parts?
- @Natim for reviews, releasing work and deployments
- @Glandos as a co-maintainer

That's plenty of people :-) I'm unsure how we should make things happen more : don't hesitate to ask if you have questions about something you feel uncomfortable with. I'll stick around anyway, and might send some PR from time to time.

Cheers, and thank you!

**Comment by almet** [comment]
@comradekingu I've added you on hosted weblate, let me know if you need anything more from me!

**Comment by JocelynDelalande** [comment]
On my side, my few moments here were pleasant and friendly, nice micro-community. Contributing here is a breath !

But I'll not take any commitment in maintainership… I prefer trying to be more regular on https://github.com/YunoHost-Apps/ihatemoney_ynh  :-).

Anyway, expect small contributions / comments from time to time. As it already have be done.

<3 on you all code crafters, translaters, beer brewers and others !

**Comment by almet** [comment]
Thank you all for this nice discussion. I'll close it as I think we know have a set of people willing to do some work on the project. Thanks to everybody involved, and I'm really happy that this project goes forward :-)

See you in a bit!
