### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by 35609902357** [spiral-project/ihatemoney#522]
The [website](https://ihatemoney.org/) does not have a privacy policy stating what and how data is collected, stored and eventually shared.

**Comment by almet** [comment]
Thanks for taking the time to open this issue. I believe it's a duplicate of https://github.com/spiral-project/ihatemoney/issues/348, but still needs to be addressed!

**Comment by qoheniac** [comment]
This issue was closed but I still cannot find a privacy policy.

**Comment by almet** [comment]
Yes, please direct the discussion and efforts in #348. Cheers.
