### ISSUE TITLE
Add isort support.

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#527]
See https://github.com/Kinto/kinto/pull/1799
See https://github.com/Kinto/kinto/pull/2276

**Comment by Glandos** [comment]
I agree.
I already use black on other projects, without any issue. I only run it manually, but it's still very useful to forget about formatting.
isort is also a nice thing to have.

**Comment by almet** [comment]
That would be nice, and is easy to add :-)

**Comment by almet** [comment]
I actually did it for black https://github.com/spiral-project/ihatemoney/commit/dc05d1cd17a4f63078f49f2d234e3d58725d5a3d
