### ISSUE TITLE
Make translation documentation more accessible.

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#534]
It seems the "how to translate" section of the docs is not easy enough to follow. Especially, if one want to change an already existing string.

Here are a few steps I've given in another issue. We might want to take some of these steps to put in the docs : 

- Clone the project locally using git clone URLOFTHEREPO and create a branch to work on using git checkout -b member-add-button
- Find the string you want to change / translate. It's in this block
- Change the text you want to change
- Run make update-translations so that the new strings are detected
- Open a pull request so we can review what you've done.

**Comment by devil-cyber** [comment]
can I work on this issue

**Comment by Natim** [comment]
Please file a PR with your proposal.
