### ISSUE TITLE
Icon is too small

### ISSUE THREAD

**Issue by indatwood** [spiral-project/ihatemoney#543]
*Hi, and thanks for this project, it's great :-) I just discovered it and I'm opening a few issues here and there to propose feedback. Hope it's the right way to do things around here!*

The [icon used as a favicon](https://raw.githubusercontent.com/spiral-project/ihatemoney/master/ihatemoney/static/favicon.ico) is too small for my eyes, or maybe it depends on the colors used, but I find it almost useless, and even counter-productive!

There are plenty of existing icons provided with CC license by the Nount project. What about this one, for instance?

https://thenounproject.com/search/?q=money&i=1406358

**Comment by almet** [comment]
Hi, thanks for opening the issue, that's appreciated, and thanks for the kind words :-) 

I'm okay with updating the current icon, this one is not really handy! Not sure about the one you're proposing though, it looks good, but I'm not sure it'll show properly as a favicon.

**Comment by najann** [comment]
Hi there!
I just came across this project and already added some translations using weblate :)
What do you think of the following icons as an alternative for the current favicon?
<table>
<td><img width="90%" alt="Screenshot 2020-05-26 at 12 23 23" src="https://user-images.githubusercontent.com/47032941/82890161-0943f180-9f4c-11ea-9b48-2300783a070a.png"></td>
<td><img width="70%" alt="Screenshot 2020-05-26 at 12 25 15" src="https://user-images.githubusercontent.com/47032941/82890168-0ba64b80-9f4c-11ea-9f60-b8184beafa6c.png"></td>
<td><img width="90%" alt="Screenshot 2020-05-26 at 12 25 15" src="https://user-images.githubusercontent.com/47032941/82889662-5ecbce80-9f4b-11ea-9fa3-4ddab92df343.png"></td>
</table>

**Comment by Glandos** [comment]
I like the second one. There are also nice ones in https://thenounproject.com/search/?q=money%20share
Like https://thenounproject.com/term/average/2028785

**Comment by allanqin** [comment]
Hi, I'm looking for my 1st open source project to contribute to. Is anyone currently working on this?

**Comment by najann** [comment]
@allanqin I had the same intention but feel free to work on this issue now!

**Comment by Sammed98** [comment]
I have made a pull request for this issue #675 . Please have a look.

**Comment by Glandos** [comment]
I feel a little uncomfortable with a single € or $, for being less inclusive. However, money lacks a universal symbol (¤ is know by nearly no one), and the dollar sign fit this role since the end of the WWII now…
Do you think we need something with a currency sign? With coins or banknotes?

**Comment by almet** [comment]
(we can remove the $ sign)

**Comment by Glandos** [comment]
I found https://thenounproject.com/term/money/2796491/ that's nearly the same, without the dollar sign, and with less pixels, so it can fit better in a favicon:
![image](https://user-images.githubusercontent.com/297578/137645571-800f51f7-68e5-4c41-8037-062695cca67a.png)

I was trying to find an icon with a coin and/or banknote and a share/split sign but it's very difficult. There is too much choices out there ;)

**Comment by almet** [comment]
That will do I think :-)

**Comment by bayquen** [comment]
Hello! I think 2B has more character than 3B because of the arrows on the top and bottom portions. I think the arrows represent the idea of transactions (money constantly moves around...). 3B looks more generic just because of the straightened currency bill icon in the middle.

**Comment by bcronald** [comment]
Hi! I came across this while looking for first-timer contribution issues. I have made a rough sketch using Inkscape. I will attach the exported png here and can upload the svg at appropriate place later. Thanks.
![I_Hate_Money](https://user-images.githubusercontent.com/6449165/165772893-22348f56-c197-44c3-a294-ebc5e75ad85e.png)
