### ISSUE TITLE
Is requirements.txt honored ?

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#545]
Digging a #540, asking myself why werkzeug 1.0 got installed , I was wondering if requirements.txt got used at all, 

After installing via pip, here is what `pipdeptree` gives :
```
ihatemoney==4.1.3
  - blinker [required: Any, installed: 1.4]
  - email-validator [required: Any, installed: 1.0.5]
    - dnspython [required: >=1.15.0, installed: 1.16.0]
    - idna [required: >=2.0.0, installed: 2.9]
  - flask [required: Any, installed: 1.1.1]
    - click [required: >=5.1, installed: 7.1.1]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 1.0.1]
  - flask-babel [required: Any, installed: 1.0.0]
    - Babel [required: >=2.3, installed: 2.8.0]
      - pytz [required: >=2015.7, installed: 2019.3]
    - Flask [required: Any, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
    - Jinja2 [required: >=2.5, installed: 2.11.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - pytz [required: Any, installed: 2019.3]
  - flask-cors [required: Any, installed: 3.0.8]
    - Flask [required: >=0.9, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
    - Six [required: Any, installed: 1.14.0]
  - flask-mail [required: Any, installed: 0.9.1]
    - blinker [required: Any, installed: 1.4]
    - Flask [required: Any, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
  - Flask-Migrate [required: Any, installed: 2.5.3]
    - alembic [required: >=0.7, installed: 1.4.2]
      - Mako [required: Any, installed: 1.1.2]
        - MarkupSafe [required: >=0.9.2, installed: 1.1.1]
      - python-dateutil [required: Any, installed: 2.8.1]
        - six [required: >=1.5, installed: 1.14.0]
      - python-editor [required: >=0.3, installed: 1.0.4]
      - SQLAlchemy [required: >=1.1.0, installed: 1.3.15]
    - Flask [required: >=0.9, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
    - Flask-SQLAlchemy [required: >=1.0, installed: 2.4.1]
      - Flask [required: >=0.10, installed: 1.1.1]
        - click [required: >=5.1, installed: 7.1.1]
        - itsdangerous [required: >=0.24, installed: 1.1.0]
        - Jinja2 [required: >=2.10.1, installed: 2.11.1]
          - MarkupSafe [required: >=0.23, installed: 1.1.1]
        - Werkzeug [required: >=0.15, installed: 1.0.1]
      - SQLAlchemy [required: >=0.8.0, installed: 1.3.15]
  - flask-restful [required: Any, installed: 0.3.8]
    - aniso8601 [required: >=0.82, installed: 8.0.0]
    - Flask [required: >=0.8, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
    - pytz [required: Any, installed: 2019.3]
    - six [required: >=1.3.0, installed: 1.14.0]
  - Flask-script [required: Any, installed: 2.0.6]
    - Flask [required: Any, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
  - flask-sqlalchemy [required: <3.0, installed: 2.4.1]
    - Flask [required: >=0.10, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 1.0.1]
    - SQLAlchemy [required: >=0.8.0, installed: 1.3.15]
  - flask-wtf [required: Any, installed: 0.14.3]
    - Flask [required: Any, installed: 1.1.1]
      - click [required: >=5.1, installed: 7.1.1]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.1]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
```

These requirements seems to match only those in setup.cfg (which have no version constraint), and not those in requirements.txt.

If requirements.txt is supposed to be used, how so ?

I think I am missing something magic 🧙‍♀️

**Comment by Glandos** [comment]
`requirements.txt` is only used bu `pip` when called with`-r requirements.txt`. When using `pip install ihatemoney`, the listed dependencies in `setup.cfg` are used.
There surely is a way to use the same list, but I don't know it. And it may be hacky :smile:

**Comment by JocelynDelalande** [comment]
Ok, that is what I feared.

That seems quite inconsistend and dangerous to me :-/. We have absolutely no requirement on deps versions on setup.cfg.

It seems like a situation where devs test with a deppendencies set, and users install another deps set :-p.

I could try to copypaste some hack I saw in other projects I work on to use the requirements.txt from the setup.py/cfg.

Otherwise, we could also just drop the use of requirements.txt in favor of setup.py/cfg

WDYT ?

**Comment by almet** [comment]
I believe I introduced the problem in https://github.com/spiral-project/ihatemoney/pull/483, sorry about it :-)

Previously, `requirements.txt` represented a known working set, [see the docs for more info](https://ihatemoney.readthedocs.io/en/latest/contributing.html#how-to-release). @Natim is the one knowledgeable about this, and he might have good insights about what we should do now.

My take on this would be : 

- pin the dependencies in `setup.cfg` **in master**
- remove `requirements.txt` in favor of using only the information in `setup.cfg`
- keep `dev-requirements.txt` with no version specified, so we can detect bugs
- integrate with dependabot so we can know when new releases exist, and we can see directly if they break our tests
- each time we release, update the dependencies to a known working set in `setup.cfg`.

**Comment by indatwood** [comment]
I believe `dev-requirements.txt` contains only extra package information, useful for devs, so @almet, it seems that what you're proposing is that we replace the `dev-requirements.txt` with just a list of requirements with no pinning, but not specific to dev?

**Comment by Glandos** [comment]
After a bit of reading, I think this is interesting:
- https://packaging.python.org/discussions/install-requires-vs-requirements/
- https://caremad.io/posts/2013/07/setup-vs-requirement/

The second one is referenced by the first. Basically, it says that two lists are made for different purposes.

But the second article propose a nice solution. Having this in `requirements.txt`:
```
--index-url https://pypi.python.org/simple/

-e .
```
This will make `pip install -r requirements.txt` use the list requirements provided by the `setuptools` declaration.

And by the way: we should not pin version, just add bounds if needed, to avoid blocking users from upgrading.

I am ready to build this list in `setup.cfg` if you want.

**Comment by eMerzh** [comment]
do you guys have feelings about an higher level package manager like https://python-poetry.org/ ?

i think with the lock file & all it can help solve our issues.

**Comment by JocelynDelalande** [comment]
First take on this (that means, totaly open to discussion and to change my mind).

I read a bit about poetry, in its documentation. It seems really like a powerful, consistent and neat tool. I think there is nothing. I'd love to test it myself.

But. I have the feeling that there is no issue that we face that cannot be solved without using more standard tooling.

It's expert tooling. Using that kind of tooling freak out newcommers, especially for new contributions. 

In the balance « easy contributable project » vs « very perfect tooling satisfying experts », I think, for IHateMoney, my take goes to the first option here :).

**Comment by almet** [comment]
+1 to keep the project easy to contribute, of course. That being said, that's not clear to me what the process would be, and, quite frankly, the "how to publish" on our documentation is already kinda messy (read: why not poetry, shouldn't we try first if it helps solving our issues?)

That's not clear to me who should solve this, and it seems "pretty urgent" if the current releases are impacted ;-)

**Comment by eMerzh** [comment]
Hey don't want to argue to much here, 
but i'm also +1 for a project easy to contribute.
The thing is that unlocked deps are already an issue for contributors (new or old) as we can see here.
Poetry is only a single tool (like virtualenv you describe in the doc) and is becoming quite popular.
Also i really think that for new contributors we should concentrate on a fully integrated docker for dev . The current one only do stable release or github-master, you can't start playing with it to add a feature.

anyway, don't get me wrong i don't particularly advocate for poetry, i just think the current situation is probably not easier with standart tools.

**Comment by JocelynDelalande** [comment]
Thanks for the chat.

So I guess after this discussion we can just move forward and look at any solution that someone would submit via a PR, being with poetry (that add some tooling, but may ease some things also).

**Comment by Natim** [comment]
Usually I tend to keep projects version up-to-date as much as possible.

Since we want to be able to install ihatemoney from pypi we should keep dependencies in setup.cfg, it seems a good idea to me to pin them there and then plug dependabot to the repository in order to keep them up-to-date.
