### ISSUE TITLE
ihatemoney.org expire dans 14 jours

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#548]
Hi, I've just received this message from Gandi, and the hosted domain needs to be renewed.

In the past, I've payed it myself or I've asked the users to contribute via a kind of crowdfunding. This time, if it's possible, I would like to not deal with this.

Let me know if you're happy to deal with this :-)

> Cher client,
> 
> Vous recevez ce message car vous êtes le contact sur le nom de domaine ihatemoney.org
> 
> Celui-ci va arriver à échéance au Registre dans 14 jours, soit le 20 avr. 2020 09:37 UTC.
> 
> Pour effectuer le renouvellement, veuillez vous rendre sur le site de Gandi en cliquant directement sur le lien ci-dessous:
> 
> https://www.gandi.net/renew?domain_list=ihatemoney.org
> (si le lien n'apparaît pas sur une seule ligne, veuillez copier-coller l'adresse entière dans votre navigateur)
> 
> Enfin, sachez que si vous ratez la date limite de renouvellement, votre nom de domaine passera en statut "restaurable" entre le 03 juin 2020 23:37 UTC et le 04 juil. 2020 09:37 UTC. Notez toutefois que le prix de cette opération peut être bien plus élevé que le prix d'un renouvellement classique.

cc @Natim @JocelynDelalande @Glandos

**Comment by Glandos** [comment]
I am OK to pay for 1 year from my personal fund. If someone want to add a bit, then we can sum it up.

Also, I already have a Gandi account, if you need to transfer the ownership.

**Comment by eMerzh** [comment]
@Glandos i can probably put a few euro too if needed, 
maybe we can start adding a "donation" on github or some other plaftorm to make this more official and recurring ?

**Comment by JocelynDelalande** [comment]
Hi ! @eMerzh good idea :+1:. @almet if we manage to get more than enough that way, maybe hosting of ihatemoney.org could go community-funded as well ?

Less fundamental : I'd prefer donations on something more ethical than github, like liberapay.

**Comment by indatwood** [comment]
Neat. Opening a donation fund for this seems a good idea !

For the hosting, I remember this is community hosted thanks to always data. (I had troubles to find it, but the info is [here](https://mailman.alwaysdata.com/hyperkitty/list/info@ihatemoney.org/thread/4LOQRI5VEAJJSZDRGTR2VBSIKGKJASAI/)).

(Which makes me think we should probably make this email list more visible!)

**Comment by JocelynDelalande** [comment]
>For the hosting, I remember this is community hosted thanks to always
>data. 

Oh sorry, i forgot about that :x. Thanks for the reminder, and thanks to them !

**Comment by almet** [comment]
Seems you're on it, awesome :-) I don't believe I need to transfer the domain, using the link in the description of the issue should be issue to renew it!

**Comment by Glandos** [comment]
[**@almet**](https://github.com/almet) commented on [6 avr. 2020 à 00:06 UTC+2](https://github.com/spiral-project/ihatemoney/issues/548#issuecomment-609492348 "2020-04-05T22:06:53Z - Replied by Github Reply Comments"):
> Seems you're on it, awesome :-) I don't believe I need to transfer the domain, using the link in the description of the issue should be issue to renew it!

Indeed. I renewed it just now, for 1 year. I paid using instant transfer, so it should be effective quite fast.

That's the first time I pay for something that I don't own, and I don't even have the confirmation of the owner :)

**Comment by Glandos** [comment]
https://whois.gandi.net/fr/results?search=ihatemoney.org

> Registrar Registration Expiration Date: 2021-04-20T09:37:57Z

By the way, there are personal data in here, I don't know if .org allows you to hide it, but you should try.

**Comment by almet** [comment]
Reopening this, since it's about to expire again.

Here's the mail I just received : 

> Cher client,
>
> Vous recevez ce message car vous êtes un contact pour le nom de domaine ihatemoney.org avec le compte ou l'organisation almet.
>
> Nous vivons en ce moment une période inédite. Face à cette crise de santé publique internationale, nous sommes conscients que les priorités sont redéfinies.
> Nous sommes toutefois tenus de vous informer que votre domaine ihatemoney.org expire dans 60 jours, soit le 20 avr. 2021 09:37 UTC.
> Si vous souhaitez conserver ce nom de domaine, vous devez effectuer le renouvellement de celui-ci avant cette date. Le domaine sera renouvelable au tarif normal jusqu'au 03 juin 2021 23:37 UTC
>
> IMPORTANT : sachez que si vous ratez la date limite de renouvellement, votre nom de domaine passera en statut "restaurable" entre le 03 juin 2021 23:37 UTC et le 04 juil. 2021 09:37 UTC. Notez toutefois que le prix de cette opération peut être bien plus élevé que le prix d'un renouvellement classique.
> Pour effectuer le renouvellement, veuillez-vous rendre sur le site de Gandi en cliquant directement sur le lien ci-dessous :
>
> https://www.gandi.net/renew?domain_list=ihatemoney.org (si le lien n'apparaît pas sur une seule ligne, veuillez copier-coller l'adresse entière dans votre navigateur)

**Comment by almet** [comment]
>  maybe we can start adding a "donation" on github or some other plaftorm to make this more official and recurring ?

I believe that would be a good choice :-) In the past, I asked the most active people using IHM if they wanted to pay for it, and received quite a good feedback. (Not sure it's okay regarding the law to use their email to contact them like this, but well… that's what I did!)
