### ISSUE TITLE
Integration with translation platform

### ISSUE THREAD

**Issue by eMerzh** [spiral-project/ihatemoney#563]
we should definetly integrate our repo with the translation system, actually weblate.

We might also explore new possibilities like lingohub or transifex if needed

_Originally posted by @Natim in https://github.com/spiral-project/ihatemoney/pull/539#issuecomment-617064016_

**Comment by Natim** [comment]
Yes I just discovered that people where using weblate. Do you know if there is a PR mecanism with Github ?

I just talked with the CEO of LingoHub and he agrees to give us a free account for I hate money.

**Comment by indatwood** [comment]
It seems that we are currently using weblate, and it should be opening PRs automatically when new translations are done on the platform (see https://github.com/spiral-project/ihatemoney/pull/510 for an example).

I know that weblate is open source and offers free access to open source projects, and I believe it's the case for I Hate Money.
