### ISSUE TITLE
Upgrade to WTForms 2.3.1

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#567]
It seems that the way we add some errors breaks going from WTForms 2.2.x to WTForms 2.3.x

It might be because of https://github.com/wtforms/wtforms/pull/568

**Comment by symphorien** [comment]
Is WTForms 2.1 ok ?

I'm trying to bump ihatemoney from 4.1 to 4.1.4 on NixOS 20.03 (which is a stable release, so bumping WTForms should be avoided if possible).

**Comment by Glandos** [comment]
I am using Debian/testing, and the WTForms package was migrated to 2.2 on 2018-10-06. I *think* that it was working nicely with 2.1, but I can't be sure of that.
If I have time, I can change the `setup.cfg` and run tests. They are not perfect, but quite complete anyway.

**Comment by zorun** [comment]
Looking at the WTForms changelog for 2.2, I don't see anything that we rely on.

Form processing mostly didn't change between ihatemoney 4.1 and ihatemoney 4.1.4, so if it worked with 4.1 it should continue to work fine with 4.1.4 as well.

**Comment by symphorien** [comment]
Tests do pass with 2.1 so I'll go for it. Thanks.
