### ISSUE TITLE
Point to playstore/fdroid app rather than nerdy git

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#597]
The smartphone icon points to https://gitlab.com/eneiluj/moneybuster

This is not nice for « simple users ». As, on earth, « simple users » are more numerous than « app developpers », maybe we could point to something more user-friendly :-)

**Comment by Abo7atm** [comment]
Is anyone working on this? I'd like to work on it. Please give me a little explanation about this issue.

**Comment by Glandos** [comment]
![Screenshot_2020-04-29 Account manager](https://user-images.githubusercontent.com/297578/80640181-545d0880-8a63-11ea-9f86-ab63e97cf7ff.png)
The red icon at the bottom is a link to a smartphone application. Right now, the link is pointing to the source code, and for a better user experience, it should point to the application store where the user can install the application in one click.

**Comment by MagicFab** [comment]
A bigger dowload button at the top linking to a download page pointing to F-Droid, Play Store and Apple Store would be more intuitive IMO. 

See this as an example : https://jitsi.org/#download

**Comment by JocelynDelalande** [comment]
Thanks for suggestion @MagicFab ; I have been thinking about the big download button and I think this is too much clutter for regular users.
It is as like all those users-hungry websites which choose to show subscription form at 1-click distance but login form at 2-click distance.

Those are patterns prioritizing agressively new user adhesion over regular users comfort.

I'd like we take care about regular users, we are not running after users or state, but making convivial tool (or I hope so :-)).

Suggestion :

## mobile apps Icons (bubles)

Replacing the smartphone icon with two bubble icons : 

- one f-droid icon
- one google-play

Those being direct links to app pages in the stores.

Those icons are targetted at desktop users, to let them know that app exist, not for android users (except as fallback), see after why…

## Adding Meta tag

- adding a `<meta>` tag to indicate semantically the existence of the app https://developers.facebook.com/docs/applinks/metadata-reference AFAIK, the effect of that is prompting the user if s·he wants to install the app on first time he comes on the website.

Any opinions ?

**Comment by MagicFab** [comment]
I understand your comment about looking hungry for users. It's the first thumb down I've earned ! :smile:  At the same time keep in mind the bottom of the page is probably the last place people will look for a download option. 

When you land on https://ihatemoney.org/ it looks like a web app (**only**). I maintain that a single "Download the mobile app" or similar clear option at the top would benefit adoption. Linking to a dedicated download page is important so the apps can be presented by themselves.

If we want to make it more balanced, less aggressive, then maybe setup a simple menu at the top including "About", "Download" and "Contribute" like most projects do. After all users could be contributors and I see such information as important as the rest.

Oh and let's not forget linking to the App store for iOS. I had a hard time finding a compatible app.

**Comment by JocelynDelalande** [comment]
I hope you took well my comment and thumb down. I appologize if it hurted, the thumb down was about one suggestion you made, not about you as a person. I like to chat and elaborate ideas for ihateoney with you, and I value your contribution here :-).

> If we want to make it more balanced, less aggressive, then maybe setup a simple menu at the top including "About", "Download" and "Contribute" like most projects do. After all users could be contributors and I see such information as important as the rest.

I'm mixed about it. I think my current opinion remain at the moment : bottom buttons + meta tag seems a good clutter vs visibility compromise to me.

> Oh and let's not forget linking to the App store for iOS. I had a hard time finding a compatible app.

Oh, I did not even know it existed ! Where ? If so, we clearly have to highlight it more ! :). Thanks for pointing at it.

**Comment by CubixPro** [comment]
Is this issue open or is it resolved?

**Comment by Glandos** [comment]
There was an attempt in #598. You can find more discussion there, and especially the [last one](https://github.com/spiral-project/ihatemoney/pull/598#issuecomment-626169426). My guess is that we need to create a new page within the project to point out different alternative clients.

**Comment by Sammed98** [comment]
If this issue has been cleared, why is the issue still open. But I don't think the button links to f-droid or play store link. 

I am just a new to this and wanted to contribute to this project. I cloned this repository and the button linked to the GitLab and not the play store link. So, I want to understand whether this still needs the changes or can be closed.

**Comment by Glandos** [comment]
Indeed, a modification was accepted in #598 but it is not the final goal, so this issue is still opened. See @JocelynDelalande comment: https://github.com/spiral-project/ihatemoney/issues/597#issuecomment-623154318
