### ISSUE TITLE
Currency: switching back to "no currency" gives unexpected results

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#599]
When using a default currency in a project, it is possible to add bills in various currencies and they will be converted to the default currency.

However, switching back to "No currency" in the options gives unexpected results:

- new bills are added without currencies (this is expected)
- existing bills keep their currency (this is expected)
- however, the converted amounts still reflect the previous default currency!

This is really weird: for existing bills that had a currency, "How much?" and "Amount" may show different values, without any way to know the currency in which "Amount" is displayed. In addition, if changing again to a new default currency, bills with no currency will be converted to the new default currency while they were probably intended as the old default currency. In short: it's a mess.

I see no easy way to fix this in the general case.  I think the simplest way is to disallow switching back to "No currency".

An alternative solution (but more complicated) is to allow switching back to "No currency" only if all bills are in the same currency, and remove the currency from all bills.

**Comment by zorun** [comment]
Here is an extreme example:

- set default currency to JPY
- add bills in EUR and GBP
- switch back to "No currency"
- add a new bill (without currency)

The result is shown below:

![ihm-no-currency](https://user-images.githubusercontent.com/731144/80703583-523a8e80-8ae3-11ea-8ce4-bc278cda8b42.png)

For the bills in EUR and GBP, the "Amount" column is still in JPY but this is not shown anywhere. For the new bill without currency, it only makes sense to interpret it as JPY because otherwise it's inconsistent with other bills.

Then I switch the default currency to PLN:

![ihm-no-currency-2](https://user-images.githubusercontent.com/731144/80703584-52d32500-8ae3-11ea-9614-c1cf8173a32d.png)

The bill with no currency has been converted to PLN.

**Comment by MagicFab** [comment]
Where do you see default currency ? I don't see this in the web interface.

**Comment by zorun** [comment]
@MagicFab the default currency can be changed in the project settings

Obviously, you need a recent version of i hate money, currency support was added only recently.

**Comment by Glandos** [comment]
A third solution would be to convert everything to the same currency before switching to "No currency", and drop all of them.

But honestly, it would much simpler to check all bills currency, and disable "No currency" in the dropdown menu if some of them are different. We could add a small explanation.

**Comment by Glandos** [comment]
But, I have to add that the current behavior is weird anyway. Switching back to "No currency" should remove currencies, and not keep the old ones "just in case".
