### ISSUE TITLE
Rethink how the demo project works

### ISSUE THREAD

**Issue by indatwood** [spiral-project/ihatemoney#609]
Currently, the demo project is just a special project that we reset now and then when it's too cluttered.

I think of a least one better ways this could be :

Have a demo project which is unique to each user, generated on the fly and destructed a few hours later. On this project members are already created and a few expenses are there.

We might want to display something special for this project so it's not thought about a "real" one.

What do you think?

**Comment by zorun** [comment]
Good idea! :+1: 

The user would need to be informed of the project password, because it is needed to change project settings.

Also, a use-case of the demo project is to send a link to show something interesting like a bug. This should still be possible, which means that a lifetime of maybe 1 week would be good. It's still infinitely less than the current lifetime :)

**Comment by Glandos** [comment]
Filling the demo project with some data can be a good idea.

Having temporary demo projects, one per user, seems to add a lot of conditions in code, with too few advantages to me.

If the goal is to avoid maintenance on the demo project, we should add some tools for that, on top of `ACTIVATE_DEMO_PROJECT`.

**Comment by indatwood** [comment]
> If the goal is to avoid maintenance on the demo project, we should add some tools for that, on top of ACTIVATE_DEMO_PROJECT.

What do you have in mind?

**Comment by Glandos** [comment]
A Python script that can clear the demo project based, or reset it to an initial state via JSON. It could be run with cron-like tools.

**Comment by indatwood** [comment]
It seems a script like this already exist, we might just want to populate the demo then :-) and document how the cron should be setup.
