### ISSUE TITLE
The private code is no longer stored or sent in cleartext

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#610]
Since a few years already (#286), we hash a project password ("private code") and don't store it in clear text. I just looked and we also don't seem to send it by email.

However, the tooltip on the home page (`ihatemoney/templates/home.html`) still says:

> This access code will be sent to your friends. It is stored as-is by the server, so don't reuse a personal password!

This text should be changed. The code is used for connecting to the project and to change its settings. It is never sent to anybody and is no longer stored "as-is" by the server. It is possible to invite people to a project without telling them the private code, this should probably be hinted here.

Also, we call that "private code" everywhere else, not "access code".

**Comment by rajat641** [comment]
Hi @zorun Can I work on this ??

**Comment by Glandos** [comment]
@rajat641 Yes, you can, nobody is currently working on this. Thanks for taking care of it :+1:

**Comment by rajat641** [comment]
Hi @Glandos @zorun ,
I have created a PR for this fix. Request to have a look. Here is the PR link- https://github.com/spiral-project/ihatemoney/pull/623

**Comment by comradekingu** [comment]
@rajat641 "Make an access code and send it to your friends"?
