### ISSUE TITLE
Reword "see" into "show"

### ISSUE THREAD

**Issue by Glandos** [spiral-project/ihatemoney#621]
@comradekingu raised the issue that "see" is not clear for the action that go the detailed page of an item in a table. Currently, it's used in:
- Dashboard for each project https://github.com/spiral-project/ihatemoney/blob/a8e74c98df44fc7632c036e8e534d93e8fc4de48/ihatemoney/templates/dashboard.html#L19
- Bill list for each bill https://github.com/spiral-project/ihatemoney/blob/981edd413acfdd4786faf5439d2a05d6d7e4649e/ihatemoney/templates/list_bills.html#L160

The [suggested wording](https://hosted.weblate.org/translate/i-hate-money/i-hate-money/en/?checksum=d99eb72c816b3f93) could be "Show" instead.

My guess is that "see" was made from "voir" in French which is the same word (in some case) for both "see" and "show". But "show" could be a better choice.

Some opinions?

**Comment by comradekingu** [comment]
It is the same problem as using "Go" for open.

**Comment by Glandos** [comment]
[**@comradekingu**](https://github.com/comradekingu) commented on [14 mai 2020 à 22:16 UTC+2](https://github.com/spiral-project/ihatemoney/issues/621#issuecomment-628864125 "2020-05-14T20:16:04Z - Replied by Github Reply Comments"):
> It is the same problem as using "Go" for open.

I was not able to find "Go". Was it removed since your comment?

**Comment by comradekingu** [comment]
@Glandos That was just an example. :)
