### ISSUE TITLE
Display email address of administrator in error messages related to emails

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#626]
Once #595 is merged, we will show an error message to the user if the email configuration of the server is broken.

In addition to that, it could be useful to give the email address of the server administrator in the error message, so that the user can actually report the issue.

@Glandos suggested using `MAIL_DEFAULT_SENDER`

Some limitations we should probably put in place:

- don't do that if public project creation is forbidden (because it would reveal more information to unauthentified users)
- check that `MAIL_DEFAULT_SENDER` is different from the default value (budget at notmyidea etc). If email configuration is broken, there's a good chance that `MAIL_DEFAULT_SENDER` is also not configured correctly.

Also, we should display the error message for a longer time to allow the user to see the email address: currently, messages disappear after just a few seconds.

**Comment by almet** [comment]
I like this :-)

**Comment by zorun** [comment]
We implemented all of this.
