### ISSUE TITLE
Chinese translation is not taken into account

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#627]
Several new languages were added with #613.

For all languages except Chinese, this works fine: after selecting the language in the top-right menu, most text is translated in the interface.

However, it does not work with Chinese: even though the translation is mostly complete, nothing happens and all text stays in English in the interface.

It may be that we are doing something wrong with the language codes, but I couldn't find the issue...

**Comment by zorun** [comment]
So, simply renaming `ihatemoney/translations/zh_HANS-CN/ to `ihatemoney/translations/zh_Hans/` fixed the issue.

Now we have to either convince weblate to change its language code, or configure Babel to accept weblate's language code...

**Comment by Glandos** [comment]
If I tested everything correctly, weblate doesn't care using `zh_Hans` instead of `zh_HANS-CN`. So I just did the same commit as yours.

**Comment by zorun** [comment]
Ah cool, thanks, I didn't think weblate would be happy if we just moved the folder!
