### ISSUE TITLE
History test case fails with MySQL

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#632]
The work-in-progress CI on postgresql and mysql (see #602 and #631 ) uncovered its first bug :)

The testcase that fails with MySQL is `HistoryTestCase.test_disable_clear_no_new_records`:

> sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1093, "You can't specify target table 'bill_version' for update in FROM clause")
> [SQL: DELETE FROM bill_version WHERE bill_version.id IN (SELECT bill_version.id AS bill_version_id 
> FROM bill_version INNER JOIN person ON bill_version.payer_id = person.id 
> WHERE person.project_id = %(project_id_1)s)]
> [parameters: {'project_id_1': 'demo'}]
> (Background on this error at: http://sqlalche.me/e/2j85)

See https://travis-ci.org/github/spiral-project/ihatemoney/jobs/690649479 for more details.

@Andrew-Dickinson could you have a look when you have time?

**Comment by Natim** [comment]
Apparently it is a MySQL specific error : https://stackoverflow.com/a/14302701/186202

**Comment by zorun** [comment]
So, the simpler version below should work for MySQL and PostgresSQL, but fails with SQLite...

```python
BillVersion.query.filter(BillVersion.payer_id == Person.id).filter(Person.project_id == project.id)
```

With sqlite:

```
NotImplementedError: This backend does not support multiple-table criteria within DELETE
```

https://docs.sqlalchemy.org/en/13/changelog/migration_12.html#orm-support-of-multiple-table-deletes

**Comment by almet** [comment]
FWIW, I was trying to reproduce the issue locally and it seems that it's now possible in recent versions of MariaDB (see https://mariadb.com/kb/en/update/#update-statements-with-the-same-source-and-target).
