### ISSUE TITLE
New user management

### ISSUE THREAD

**Issue by QuentinRoy** [spiral-project/ihatemoney#64]
As previously discussed with Alexis (who didn't agree with me at this time), I think the delete user functionality is confusing and unecessary.

Here is my idea:
- No user deletion at all, if a user is part of a displayed bill, he is in the balance list BUT
  - Users with a balance of 0 are automatically hidden.
  - We can show those hidden users with a button at the end of the balance list. They will be displayed at the end of the balance list (like an extension of it). They'll be sorted by last appearance.
  - Some small heuristics can be used in order to keep some users unhidden even if their balance is 0 (if the user is in the last bill sounds sufficient to me).
  - By the way, I preferred much more the previous balance list design :).
- Creation of new users at new bill creation :
  - As I said, I don't like the checkboxes stuff. I think a text line with autocompletion (like the one we have for the recipient fields of our mail client) would be cool. It allows to create a new user directly (simply by writing his name). We also can keep the mouse interaction by adding a user in the bill by clicking on his name in the balance list on the left.
  - This is conflicting with #53 but no checkboxes means a form much more lighter. This is also conflicting with #61 without addition of difficult extra interactions (even if it may be still do-able).

What do you think ?

**Comment by almet** [comment]
I believe we won't do that for now (but it could be part of a complete redesign).
