### ISSUE TITLE
Show "External link" less prominently when creating bill

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#656]
Since #479, it is possible to add an URL as "External link" when creating a bill.

However, the field is really big and prominent in the bill creation page, even for people that do not need this feature.

It would be good to find a less prominent design, so that:

- people that don't need External links are not bothered by the additional interface
- people that need External links can still easily add them

A more general discussion about optional features is at #603 (see the example about the weights, I really like it)

**Comment by almet** [comment]
So, what about an "extra fields" clickable link which expends to a few optional fields that could be then filled?

**Comment by Glandos** [comment]
Like a simple [`details/summary`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tag?

**Comment by zorun** [comment]
It's a simple and pragmatic way to fix this, I like it.

People that want to add an external link on each bill might find it annoying, because it would require one more click for each bill. But we can start with this simple solution, and somebody could propose a better UI/UX design later if this use-case is important for them.

**Comment by zorun** [comment]
Anybody want to work on this? (I suck at web UI)

**Comment by Glandos** [comment]
I hacked something like this:

https://user-images.githubusercontent.com/297578/124379620-703bea00-dcb8-11eb-8fd3-d04bcace02d1.mp4

Does it sound good (except some margins…)

**Comment by zorun** [comment]
Excellent! :+1: 

Yeah, you probably need a slightly bigger margin between "Options avancées" and the actual fields.
