### ISSUE TITLE
ihatemoney/ihatemoney/conf-templates/ihatemoney.cfg.j2 database URI appears wrong

### ISSUE THREAD

**Issue by lemgandi** [spiral-project/ihatemoney#672]
Reads:

`SQLALCHEMY_DATABASE_URI = 'sqlite:///var/lib/ihatemoney/ihatemoney.sqlite'`

Should read:

`SQLALCHEMY_DATABASE_URI = 'sqlite:////var/lib/ihatemoney/ihatemoney.sqlite'  `

 (note 4 '/' rather than 3) When I place my sqlite database into /var/www/ihatemoney/db/ihatemoney.db in default_settings.py  with just 3 '/', I get 'internal server error'.  I presume  that most users edit this URI to point to a MySQL or PostgreSQL database.  Also, the file extension should probably be ".db" for consistency with the contents of default_settings.py.

I am just a N00b at contributing to OS projects, but I've got a lot of commercial programming experience.  I have a dev environment set up on VirtualBox. I'm hoping to use this admittedly small issue to figure out how to get changes into your code base.

**Comment by Glandos** [comment]
Thanks a lot!
