### ISSUE TITLE
Inaccurate costs repartition

### ISSUE THREAD

**Issue by stemy2** [spiral-project/ihatemoney#715]
Hello,

The costs repartition is really strange and means that everyone pay for the purchase, except the one who bough it.

I take my example: we are 7, i bough some things and the total costs are divided by 6 and i have nothing to pay even if i take advantage too of what i bough. I don't think it's supposed to work like that.

**Comment by Natim** [comment]
Maybe you forgot to add the one who paid as part as the bill sharing?

The software handle the case where someone pays for other without being part of the bill sharing.

![image](https://user-images.githubusercontent.com/229453/107259326-261e4780-6a3d-11eb-9836-e7b668e0351f.png)

**Comment by stemy2** [comment]
Nevermind, i misread my bill, everything is correct.
