### ISSUE TITLE
CSRF token has expired

### ISSUE THREAD

**Issue by stemy2** [spiral-project/ihatemoney#716]
Hello,

I'd like to connect to my project on my PC and my phone, but when i'm trying with my phone, i have the message here above. What is a CSRF token ? How can i create a valid one ?

**Comment by Glandos** [comment]
I guess you connected on the main instance https://ihatemoney.org/

A CSRF token is a string generated by the server to avoid abuse. It has a limited lifetime. It is stored as a cookie. So you have two choices:
- The page was loaded a long time ago; just reload it before logging in.
- Your browser is filtering the cookie. You can try to unblock it if you have a special browser/extension/blocker.

Can you provide us your browser?

**Comment by almet** [comment]
Hi, and thanks for the issue. I'm closing it since we're lacking information to reproduce. Don't hesitate to reopen and provide more information and steps to reproduce if it's still happening.
