### ISSUE TITLE
How to mark a bill as "paid" ?

### ISSUE THREAD

**Issue by stemy2** [spiral-project/ihatemoney#717]
Hello,

For what i saw on the website, it is possible to mark a bill as "paid", but i don't understand how, i didn't found any such option. How am i supposed to make the statistics accurate in relation to the actual refunds ?

**Comment by Natim** [comment]
![image](https://user-images.githubusercontent.com/229453/107286241-99858080-6a60-11eb-8a91-cc65a74af2a3.png)

This is how I do it nowadays, however I think something has been worked on which might not be deployed yet.

**Comment by almet** [comment]
Hi, like @natim I though this was the case, but I'm also doing this hack by adding a transaction in the opposite direction.
