### ISSUE TITLE
domain name expiration in 14 days

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#733]
Got another email from gandi for the domain name expiration so I'm creating a new issue, and closed #548.

Cher client,

Vous recevez ce message car vous êtes un contact pour le nom de domaine ihatemoney.org avec le compte ou l'organisation almet.

Nous vivons en ce moment une période inédite. Face à cette crise de santé publique internationale, nous sommes conscients que les priorités sont redéfinies.

Nous sommes toutefois tenus de vous informer que votre domaine ihatemoney.org expire dans 14 jours, soit le 20 avr. 2021 09:37 UTC.

Si vous souhaitez conserver ce nom de domaine, vous devez effectuer le renouvellement de celui-ci avant cette date. Le domaine sera renouvelable au tarif normal jusqu'au 03 juin 2021 23:37 UTC

IMPORTANT : sachez que si vous ratez la date limite de renouvellement, votre nom de domaine passera en statut "restaurable" entre le 03 juin 2021 23:37 UTC et le 04 juil. 2021 09:37 UTC. Notez toutefois que le prix de cette opération peut être bien plus élevé que le prix d'un renouvellement classique.

Pour effectuer le renouvellement, veuillez-vous rendre sur le site de Gandi en cliquant directement sur le lien ci-dessous :

https://www.gandi.net/renew?domain_list=ihatemoney.org
(si le lien n'apparaît pas sur une seule ligne, veuillez copier-coller l'adresse entière dans votre navigateur)

Nous vous conseillons très fortement d'opter pour le renouvellement automatique de vos noms de domaine si cela n'est pas déjà fait. Cette précaution simple protège d'un oubli du renouvellement de noms de domaine importants pour vous, et possiblement de leur suspension et placement en période de restauration (qui est généralement soumise à un tarif plus élevé qu'un simple renouvellement) voire la remise à disposition du nom de domaine à l'enregistrement par toute personne.

Cette option peut être activée ou désactivée via votre compte Gandi. Pour en savoir plus sur le renouvellement automatique et le renouvellement de nom de domaine chez Gandi, nous vous invitons à consulter notre documentation : https://docs.gandi.net/fr/noms_domaine/renouvellement/

Si, en raison de cette crise, votre situation remettait en cause la possibilité de procéder à ce renouvellement, nous vous invitons à contacter notre Service Client afin de vous aider à trouver une solution.

Enfin, pour information, sans action de votre part, ihatemoney.org retombera dans le domaine public aux alentours du 09 juil. 2021 09:37 UTC (la date peut varier légèrement en fonction des Registres et des fuseaux horaires).

Pendant cette période inédite, soyez assurés que nous sommes tous impliqués pour veiller au bon fonctionnement de vos services et vous garantir leur(s) continuité(s).

Nos pensées se tournent vers nos clients et toutes les personnes impactées par ces circonstances sans précédent.

N'hésitez pas à contacter notre Service Support si vous avez besoin d'aide ou tout simplement de plus d'information :
https://help.gandi.net/fr/contact/
Nous vous remercions de votre confiance.

Cordialement.

-- 

GANDI - https://www.gandi.net

**Comment by Glandos** [comment]
OK, since last year I renew the domain, I think someone else could do this now.

By the way, I just created a LiberayPay account on https://liberapay.com/IHateMoney

I set the goal to 0.4€ per week, just enough to renew the main domain. I'm about to add this in the readme.

**Comment by almet** [comment]
Thanks for doing this :-)

**Comment by almet** [comment]
I'm also wondering if we shouldn't add a way to put this information on the website itself. In the past, I used to send an email to the users asking them to finance if they wanted. The cost was higher then because it was also covering hosting the service, which is now offered by alwaysdata.

**Comment by Glandos** [comment]
Now, I clearly hesitate to donate myself. Since the money will finally be transferred on my personal account, it's a bit stupid, since it will be cut off by 5% at best.

The goal is just to show that someone already paid… Sometime, it is more attractive.

**Comment by almet** [comment]
Hi, I've sent an email to the most active users (people with more than 10 bills in a project active in the past 30 days), to ask them to pay on liberapay if they want and can.

Can you please add me to the owners there? Thanks! (https://liberapay.com/Almet/)

**Comment by almet** [comment]
FWIW, le petit code que j'ai utilisé pour récupérer les mails en question est ici : https://gist.github.com/almet/423e71aa9846d6e38d9892390e8270a2

**Comment by almet** [comment]
I'm closing the issue, we've enough money it seems :-)

**Comment by Glandos** [comment]
> Cher Client,
> 
> Nous sommes heureux de vous confirmer que le domaine enregistré chez Gandi a été renouvelé : 
> 
>   ihatemoney.org
> 
> Ce domaine a été renouvelé pour 1 an(s), et sa nouvelle date d'expiration est 2022-04-20 09:37:57.

À l'année prochaine !
