### ISSUE TITLE
4.2 release status ; delete 4.2 related branches ?

### ISSUE THREAD

**Issue by JocelynDelalande** [spiral-project/ihatemoney#772]
Hi there :wave: 

What is exactly 4.2 release status ?

It can be found here : https://github.com/spiral-project/ihatemoney/releases/tag/4.2

But I get the impression that it's a dead-end, and that 4.2x did not received the [security patch](https://github.com/spiral-project/ihatemoney/security/advisories/GHSA-67j9-c52g-w2q9) and [never got released on pypi](https://pypi.org/project/ihatemoney/#history)

I think it should not appear in [GH release history](https://github.com/spiral-project/ihatemoney/releases) as it currently does, this is misleading.

So I'm about to delete the tag `4.2` tag on the git repository but wanted a confirmation that i was not doing anything bad / wasting work.

@Glandos @Natim is it ok if I delete the `4.2` tag and `prepare-4.2` branch ?

**Comment by zorun** [comment]
Yes, it was a tagging mistake: according to semantic versioning, the next release is supposed to be 5.0 (because we drop old python versions)

I thought it was already deleted.

**Comment by zorun** [comment]
See #570

**Comment by Glandos** [comment]
@JocelynDelalande Go for deletion :boom:

**Comment by JocelynDelalande** [comment]
Thanks for your answers. Tag is now deleted, I kept the branch because, while being misnamed, this is the one used for #570.
