### ISSUE TITLE
AttributeError: can't set attribute when connecting to sqlite database with flask-sqlalchemy

### ISSUE THREAD

**Issue by KarolosLykos** [spiral-project/ihatemoney#778]
Hi, I have a problem starting the docker container.

I followed the documentation and built the image.

But when I run the container I get the following error.

AttributeError: can't set attribute when connecting to sqlite database with flask-sqlalchemy

**Comment by kofoednielsen** [comment]
I fixed this by setting the environment variable `NIGHTLY=true` in my container. This uses a Flask-SQLAlchemy=2.5.1

**Comment by KarolosLykos** [comment]
Thank you very much that fixed the problem. I tried setting up the Flask-SQLAlchemy to 2.5 inside the setup.cfg but nothing. I'm not used to python, so I don't know if that was a smart move, messing around with the configuration files :D

**Comment by kofoednielsen** [comment]
Yeah the docker file is very funny. Doesn't do much at build time, and at run time in downloads the code, builds and runs 🤷‍♂️

**Comment by zorun** [comment]
This should be better now thanks to #793
