### ISSUE TITLE
The API documentation is outdated

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#782]
I was following the documentation of the API, and the current format of API responses is quite different from the documentation.

For instance the output of `/api/projects/XXX` is completly different from https://ihatemoney.readthedocs.io/en/latest/api.html#getting-information-about-the-project

**Comment by ekand** [comment]
I am interested in this issue, and will look around and evaluate whether I am able to help with it.

**Comment by zorun** [comment]
Thanks for the first improvement! As discussed in #821 there may be more changes needed though.
