### ISSUE TITLE
Change Dockerfile to setup the app at build time instead of runtime

### ISSUE THREAD

**Issue by wrecker** [spiral-project/ihatemoney#792]
The current Dockerfile is written to download the python dependencies and setup the full app when the container starts up. This means everytime the container starts up it goes the whole process of downloading the python dependencies from PyPi and setting up the app. I was trying to bring this up in an isolated environment and realized it wouldn't work. There are other side-effects like users cannot run the `generate_hashed_password` with a built image in a single step. 

A better way to do this would be move the python setup process from entrypoint.sh into the Dockerfile and simplify the entrypoint.sh (and in turn the startup process). If the current behavior is useful for dev purposes, the project can have a separate Dockerfile.dev with a corresponding dev-entrypoint.sh.

**Comment by wrecker** [comment]
I have a PR if you would like to see review it.

**Comment by zorun** [comment]
Hi, welcome! This is definitely a change we want to have, I also don't like the current process (but I'm not a big Docker user). I'll comment on the PR.

For reference, we have another issue about Docker here: #332

**Comment by ra-ju** [comment]
Since the PR #793 has been merged, can we close this issue?
