### ISSUE TITLE
Language list is not scrollable on mobile

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#811]
I just tested on Android (with a somewhat weird browser), and I cannot scroll in the language list. French is high enough in the list to be selectable, but many languages are not that lucky.

See screenshot:

![image](https://user-images.githubusercontent.com/731144/126067813-94ddbaf3-8477-4bc6-9c09-9594a16d21d8.png)

**Comment by shreyash00007** [comment]
hey, I just got the fix of it you can add the some code to the class "navbar-collapse"
    
  .navbar-collapse {
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    -ms-flex-positive: 1;
    flex-grow: 1;
    -ms-flex-align: center;
    align-items: center;
    margin: 5px;
    padding: 5px;
    background-color: #343a40;
    width: 500px;      //adjust in desktop view
    height: 110px;        //adjust in desktop view
    overflow: auto;
    text-align: justify;
}
I tested it works, but adjust the width properly as per the desktop view .

**Comment by Flecart** [comment]
@shreyash00007 you have to open a pull request to collaborate!
Fork the repository, make new branch and open pull request

**Comment by Glandos** [comment]
[**@Flecart**](https://github.com/Flecart) commented on [18 juil. 2021 à 18:47 UTC+2](https://github.com/spiral-project/ihatemoney/issues/811#issuecomment-882084809 "2021-07-18T16:47:43Z - Replied by Github Reply Comments"):
> @shreyash00007 you have to open a pull request to collaborate!
> Fork the repository, make new branch and open pull request

For a simple file edition, you can even:
- Navigate to the file, display it
- Click on the “Pen” icon at the top right
- Edit & save
- Submit the PR

For small contributions, this is really a good way to go.

**Comment by zorun** [comment]
Fixed by #813, thanks.
