### ISSUE TITLE
💥 potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [spiral-project/ihatemoney#817]
potential security vulnerability has been disclosed to huntr platform for your repo .
plz validate them.
you can validate them via magick link sent to your mail or by signing up in huntr
https://huntr.dev/bounties/892946b8-0b8f-4592-876f-2cdf3d35e0d0/
https://huntr.dev/bounties/f9ffef38-4060-4e13-a4f2-7e7fe7dc1fe7/
https://huntr.dev/bounties/b806b9c3-48c8-44cd-bbce-918dd6d1e2ad/

**Comment by rugk** [comment]
Is that to be interpreted as a "yes"?
