### ISSUE TITLE
Handle db migration?

### ISSUE THREAD

**Issue by feth** [spiral-project/ihatemoney#83]
Hello,

I'd like to try and add a feature to this app, that requires an sql schema migration.
Do you have an opinion about the best way to properly handle schema migrations?

Basically, all tools work the same and rely on a version field (integer) stored in a special table.
If not found, table and field are created (and version assumed to be 0).
If found, application compares the field with its own schema version, and if necessary, applies required migrations.

SqlAlchemy has its own tool: http://readthedocs.org/docs/sqlalchemy-migrate
They describe the generic steps involved: http://caneypuggies.alwaysreformed.com/wiki/DevelopingWithMigrations

Googling for "flask migration", I also found https://github.com/adamrt/flask-evolution/tree/master/flaskext -however I'm not sure what it is good for.

**Comment by JocelynDelalande** [comment]
I'm not yet very familiar with flask, but I see two libs to do that :

- https://github.com/stackforge/sqlalchemy-migrate
- https://pypi.python.org/pypi/alembic

Both seems active, if someone more experimented on flask has an opinion on it, it would be handy :), as well as pointing out some software that nicely integrate those libs.

Coming from Django world, I find the migrations library for SQLA a bit disappointing :

- complicated setup
- complicated migration (eg: you seem to have to configure the target db by hand on each deployment)
- no automatic migration creation from models change

… But let's do with what exists :)

I thought for a while that we could do some DIY migrations but it would tend to be a nightmare, for example, IIRC, sqlite has no way to add a column without recreating the table.

**Comment by JocelynDelalande** [comment]
any input on that ?

**Comment by almet** [comment]
I won't invest time on this project to develop new features like this, unfortunately. Feel free to take it if you need it! I'll hapilly review and provide feedback if needed.
