### ISSUE TITLE
Custom currencies support

### ISSUE THREAD

**Issue by Glandos** [spiral-project/ihatemoney#833]
Hello, I'm not sure where it's best to ask this, so let's try here:

This new currency feature (to which I'm really looking forward), is it strictly for known "fiat" currencies ? Would custom currencies be supported ? (For example: I owe you 2 HUGS) Will cryptocurrencies be supported ?

_Originally posted by @Mageek627 in https://github.com/spiral-project/ihatemoney/issues/806#issuecomment-910885244_

**Comment by Glandos** [comment]
In fact, currencies were introduced because people need to **convert** between them. And that we can have a reasonably reliable reference for conversion rates.

Cryptocurrencies are highly volatile, so I guess it will be more difficult. And custom currencies like HUGS (which could be a neat currency btw) can't be converted, so in my opinion, it should stay with no currency.

**Comment by zorun** [comment]
+1, if you want to use a custom currency that is not easily convertible, just use "no currency" for your project. Values are just numbers, so they could mean anything (€, foocryptocoins, hugs...).

That being said, well-known cryptocurrencies are already supported as currencies: I see BTC in the output of the API we're using.
