### ISSUE TITLE
Weight is being rounded on balance member list

### ISSUE THREAD

**Issue by DanielNetoP** [spiral-project/ihatemoney#838]
Currently the user's weight are being rounded on to 1 decimal case only, so if we select 0.75 as the weight for one user and 0.25 for the other we see on the balance member list as 0.8 and 0.2 image below:
![image](https://user-images.githubusercontent.com/10155766/133506738-51e76bda-e498-4019-b56a-42993062dbc7.png)

**Comment by Glandos** [comment]
Thanks for this suggestion, I have to admit that I also like to have two decimals. Is it possible for you to add a new test case for this? I'll guess that we need to test that:
- 1.0 is displayed as 1
- 1.10 is displayed as 1.1
- 1.15 is displayed as 1.15

**Comment by DanielNetoP** [comment]
Thank you @Glandos
I've just updated the PR with the test cases.
