### ISSUE TITLE
Unable to create a new project via Api. Default currency is a required field 

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#917]
When using money buster, I'm currently unable to create a new project. 
![IMG-20211113-WA0003](https://user-images.githubusercontent.com/67073/141643218-3cd40921-4029-4673-aaef-0af9f7591f82.jpg)

**Comment by zorun** [comment]
Strange, this was supposedly fixed in #850. Are you using latest master?

**Comment by almet** [comment]
I think the deployed instance is lagging behind. @natim dont hesitate to take over à deploy it if you have spare time. I'll look later otherwise
