### ISSUE TITLE
Demo in Firefox (Internal Server Error)

### ISSUE THREAD

**Issue by grantwforsythe** [spiral-project/ihatemoney#928]
I came across this project in my search to find a free and open-source alternative to [YNAB](https://www.youneedabudget.com/).

Before creating an account, I wanted to use the [demo](https://ihatemoney.org/demo/) feature; however, I am getting an _Internal Server Error_ (500) when using `Firefox v94.0.1`.

I didn't receive this error when using `Chrome`.

**Comment by almet** [comment]
This is now solved, thanks for the report :-)
