### ISSUE TITLE
Show a QRcode to sync the project in MoneyBuster.

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#937]
It could be nice to show a QRCode to scan the webpage directly in MoneyBuster!

**Comment by almet** [comment]
This doesn't seem to be possible ATM because MoneyBuster requires a password, which we don't give to the users.

FTR, the encoded url looks like this : `http://net.eneiluj.moneybuster.ihatemoney/project_id/password`.

**Comment by zorun** [comment]
It seems it was done in #1000 ?
