### ISSUE TITLE
Add user coefficients.

### ISSUE THREAD

**Issue by Korri** [spiral-project/ihatemoney#94]
We currently use an App on Android, and is has a realy cool feature, you can assign a default percentage to each user (default and per transaction), so for example we have a couple here so they have a default percentage of 200% as they share the same money (And like that we don't need to split every purchase between the two of them).

Having this feature could be really cool.

**Comment by ametaireau** [comment]
Where are we with this? @aavenel do you want to work on it?

**Comment by ametaireau** [comment]
Another possibility is to add this coefficient information to the list of people (e.g. that would work for couples).

This seems to minimize the complexity (no change when adding the new bills) and could only when editing the users (not sure exaclty how to do that, though).

**Comment by JocelynDelalande** [comment]
+1 for the proposition of coefficients on users, I think it's a rather light feature in terms of UI, for same reasons that @berteh mentioned.

Another use case, which is quite complicated to handle without software and fits nicely with user coefficients :

- John, Mag and Bob go on holidays together
- John stays 3 days, Mag 2 days and Bob 2 days, they log their bills on IHM.

Assigning weights based on the days people stay is a nice way to handle that (doing it with spreadsheet is not straightforward).

**Comment by ametaireau** [comment]
I've updated the title of the issue. I think the other proposal (in-bill coefs) is a no-go based on the feedback we currently have.

**Comment by JocelynDelalande** [comment]
I started working on it.
As it implies schema modification, one question that remains IMHO before merging is how to handle migrations, see https://github.com/spiral-project/ihatemoney/issues/83

**Comment by JocelynDelalande** [comment]
UI proposal for users list

![screenshot-localhost 5000 2015-08-20 11-41-28](https://cloud.githubusercontent.com/assets/429633/9380467/aa7d09ac-4730-11e5-9a7f-88913156720e.png)

I suggest hiding the coefficient if everyone is x1

**Comment by aavenel** [comment]
Looks good for me, but how do you define the coefficient for each user ?

**Comment by JocelynDelalande** [comment]
> Looks good for me, but how do you define the coefficient for each user ?

Coming later, work in progress :)

**Comment by JocelynDelalande** [comment]
UI proposal for the users list to access member form
![screenshot-localhost 5000 2015-08-22 10-40-53](https://cloud.githubusercontent.com/assets/429633/9423202/9c477fb2-48ba-11e5-9bfe-e57a4cb9f770.png)

**Comment by zorun** [comment]
I guess this issue can be closed, it has been implemented by #131 :)

**Comment by berteh** [comment]
love it, and the simple way you handled it. congrats.
