### ISSUE TITLE
Integrate better with MoneyBuster on android.

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#942]
I believe we could do a better job at integrating IHM with the MoneyBuster app on android.

I'm thinking about two things : 
- Directing users to the MoneyBuster app ;
- Helping them to set-up their projects with MoneyBuster.

## Directing users to the MoneyBuster app.

Currently, we don't act differently depending on the device. It's possible to click on the "phone" icon, but you have to see it first. It's not uncommon for website to detect the platform with the request and ask the user if they want to install a mobile app.

Doing so should be fairly easy, but I wonder how much intrusive this would be for people not wanting to use the mobile app. We could use cookies to store user prefs about this for instance.

## Helping users set-up their projects in MoneyBuster 

MoneyBuster supports what I'll call here "ihatemoney links". These are links of the form `ihatemoney://{host}/{project_id}/{password}`. On a phone, when a user follows this link (and has MoneyBuster installed), it adds automatically the project to the app, which is really nice because it doesn't need to be typed manually.

So, it could be helpful to show these links to the user, or even via a QRcode on the project page.

The problem is that in IHM we don't know the project's passwords (so we can't show them to the users), and MoneyBuster doesn't support (yet?) authentication via invitation links (this is tracked in https://gitlab.com/eneiluj/moneybuster/-/issues/91).

What do you think about this? Do you have any other ideas on how the interactions between IHM and MoneyBuster could be enhanced?

**Comment by zorun** [comment]
I'm strongly against having a full-page message to "force" mobile users to install the app. It's indeed a fairly common practice, but that's really unfortunate in my opinion. If the message is discrete enough, then why not, but we already have a link to the mobile apps.

For the second part, I don't have a strong opinion, I guess an option to show a QRcode for moneybuster could be nice. However I'm not convinced about the links (outside of a QR-code), what would be the usage scenario?

**Comment by almet** [comment]
> I'm strongly against having a full-page message to "force" mobile users to install the app. It's indeed a fairly common practice, but that's really unfortunate in my opinion. If the message is discrete enough, then why not, but we already have a link to the mobile apps.

Of course, I don't want to force anybody to do anything =). I just want to have a way for them to know that a mobile app exists, because it's handy.

This would be only done for people using a mobile web browser on android (and maybe on apple iphone). If you are against this, could you please elaborate why? Thanks!

For the second part, the links are what's encoded in the QRcode, and are useful because, when you're on the phone, you can't scan the QRCode : it's on your screen, so the link would allow people to configure the app automatically.

Two usage scenarios : 
1. On your phone, you visit the project page on the website and then click on the link to configure the app. The rest is done by MoneyBuster ;
2. You visit the project page on your desktop, and you scan the QRcode with your phone, the rest is done by MoneyBuster.

**Comment by almet** [comment]
Done with #937
