### ISSUE TITLE
High integer can corrupt demo database

### ISSUE THREAD

**Issue by TechyTommy3** [spiral-project/ihatemoney#957]
So yesterday, I was trying out the demo on ihatemoney.org. And, I entered in a really high integer (something as big as 9347242149381274732472348728748723473278472843.) Now, it is easy to repair, but it requires editing your database. I did this on my own database again (nothing important is on it), and it gave me an internal server error. And yes, the ihatemoney.org demo I accidently corrupted still isn't working.
**Steps to reproduce**
1. Go into demo
2. Add a new bill
3. Add a big number, like 9347242149381274732472348728748723473278472843
Some error handling needs to be added.

**Comment by Glandos** [comment]
I don't know if it can be solved upstream, but see https://github.com/python-babel/babel/issues/821 that I just opened.

**Comment by Glandos** [comment]
And in this project, I don't know what should be a real solution. Capping the max value is not really good, there will always be a user that have a use case for this.
Maybe check the value before formatting?

**Comment by almet** [comment]
> Capping the max value is not really good, there will always be a user that have a use case for this.

I think we can cap to something really high, like 100 000 000 000. If people with this amount of money want to still use our software, they could open an issue ;-)

**Comment by Glandos** [comment]
I'll go with #989. The `decimal.MAX_EMAX` seems to be lower than required, by really high enough for our use case. @almet do you think it's the right way to workaround?
