### ISSUE TITLE
Check that language exists before setting the session cookie

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#970]
@Glandos said in #963 

> […] http://127.0.0.1:5000/lang/kikoo lead to a bad behavior: the server generates an error 500, and the user can't get out of it without calling manually /lang/en or deleting the session cookie. But it means that it could load files, only within the current directory.

We should check that the file is correct before loading it.

**Comment by almet** [comment]
Great, thanks!

**Comment by Glandos** [comment]
I was caught by the gamification of bug squashing!

**Comment by almet** [comment]
It's the right time to open more issue then! 😁
