### ISSUE TITLE
Showcase images are referenced without url_for(), resulting in buggy URLs in case of subdir install

### ISSUE THREAD

**Issue by Salamandar** [spiral-project/ihatemoney#973]
The faulty code is here :

https://github.com/spiral-project/ihatemoney/blob/ff4de78b569610e1715859e79fca1dd6ca41b94c/ihatemoney/templates/showcase.html#L36

Here you reference "/static/showcase/1.webp" but it should be `"{{ url_for('static', filename='showcase/1.webp')}}"`.

**Comment by almet** [comment]
Hey, thanks for taking the time to open a report. Are you willing to submit a pull request?

**Comment by Salamandar** [comment]
Ah, yes, I was priorizing doing a patch for 5.1.1 though.

**Comment by almet** [comment]
Not sure what you mean?

**Comment by Salamandar** [comment]
The Yunohost package uses the 5.1.1 release, not the master branch. So I first wrote a patch for the 5.1.1 branch (it's still using jpeg, instead of webp on the master branch).

**Comment by almet** [comment]
Thanks for the explanation :-) I don't think we want to maintain multiple branches with different versions though.

Is there anything blocking Yunohost from using the latest release? (or the soon-to-come release ?)

**Comment by Salamandar** [comment]
@almet Well I just did `pip install ihatemoney==5.1.1`. We don't want the package to track master, or bug tracking will be a nightmare.
You just have to release 5.1.2 and we'll drop the patch on our side xD

**Comment by almet** [comment]
Ah perfect 👍 we are working on the future release, keep posted 😊
