### ISSUE TITLE
Make "how much" field a number type

### ISSUE THREAD

**Issue by RayBB** [spiral-project/ihatemoney#984]
Right now the website lets you type (or sloppily copy) something like $122.34 but rejects it when you hit submit, showing the following error:
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/921217/150471930-4182ddfd-1281-4d02-a7af-92ef086b71f3.png">

I think it would be nice to add `type="number"  step="any"` (or maybe `step="0.01"`) to the field so that html validation warns you, and on mobile devices it will show the number keyboard.

PS: thanks for running this service it is really awesome and a great way to keep venmo, cash app, and the like from having more data on me.

**Comment by almet** [comment]
Hi, thanks for the kind words!

It's actually not a number type because you can do small computations in there, such as "5+2+3". The downside of this little trick is that we can't use the hints from the browser (like the one you're proposing).

That being said, it seems that the problem is more that the value disappears when you submit it and it fails, no? If that's the case, we could try to be smart about it and for instance remove any non digit character at the beginning and the end of the submitted field. Would that solve your issue?

**Comment by RayBB** [comment]
Oh wow that's awesome I had no idea!

It would be cool if you added a little on hover tool tip or something to let people know it can do small calculations.

But like you said, if you just stripped special characters at beginning/end that would solve 99% of the issue. Maybe not removing the value when it is invalid would be nice too so you can fix it.

Also, another small idea is that you could possibly specify input type but set the field to `novalidate` so that you're allowed to paste in other things too? This would cause the number keyboard to come up by default but not sure if there are any other gotchas. Related SO question: https://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input#comment17146094_6512618

**Comment by almet** [comment]
Thanks for the pointers! I'm not sure about not removing the values and displaying them to the users, I'm kind of afraid about cross site scripting and stuff like that.

Would you like to work on this or should we mark this as an up for grab?

**Comment by RayBB** [comment]
Please do put it up for grabs as I won't have time in the near future.

**Comment by reeyagup** [comment]
I tried to make  PR with my branch to solve this issue, except I keep getting this error: when i do 'git push'
![image](https://user-images.githubusercontent.com/57969781/151688399-f68df250-2482-4ecf-ac11-2cba6ba74191.png)

**Comment by Glandos** [comment]
@reeyagup it's normal you don't have write access to this project. You should push to your own fork first, and then open a pull request using the Github web interface. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests for more details.

**Comment by reeyagup** [comment]
https://github.com/reeyagup/ihatemoney/pull/1

**Comment by Glandos** [comment]
[**@RayBB**](https://github.com/RayBB) commented on [21 janv. 2022, 18:22 UTC+1](https://github.com/spiral-project/ihatemoney/issues/984#issuecomment-1018710775 "2022-01-21T17:22:43Z - Replied by Github Reply Comments"):
> Also, another small idea is that you could possibly specify input type but set the field to `novalidate` so that you're allowed to paste in other things too? This would cause the number keyboard to come up by default but not sure if there are any other gotchas. Related SO question: https://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input#comment17146094_6512618

I investigated on this, and it seems that using `novalidate` on the `<form>` tag disable the whole form validation. Errors still can be checked with CSS selectors and Javascript API, but we have to do the whole work manually. I have to admit that hinting mobile clients to display a numeric pad is a nice feature, but this seems costly.

**Comment by RayBB** [comment]
@Glandos thanks for investigating. Probably not wroth the effort and added complexity in that case

**Comment by Glandos** [comment]
Closing then.
