### ISSUE TITLE
Add a tooltip to advertize the computation trick on bills

### ISSUE THREAD

**Issue by almet** [spiral-project/ihatemoney#985]
> It would be cool if you added a little on hover tool tip or something to let people know it can do small calculations.
> — @raybb in https://github.com/spiral-project/ihatemoney/issues/984#issuecomment-1018710775

Let's do it :-)

**Comment by gianlucadecola** [comment]
Hi! first time here; could something like this be ok? (screenshots below)
![Screenshot from 2022-01-28 17-21-35](https://user-images.githubusercontent.com/42657588/151583756-e2e60ef2-296c-409d-957e-f9d6302b72b2.png)
![Screenshot from 2022-01-28 17-21-19](https://user-images.githubusercontent.com/42657588/151583767-4e6f4048-36d9-4722-a2cc-ca2d3382f022.png)

**Comment by Glandos** [comment]
Yes, I think the UI is correct. But maybe we can put some examples in it: `Simple operations are allowed, e.g. (18+36.2)/3`

**Comment by gianlucadecola** [comment]
Seems right to me, I've issued a pull request with the update :)

**Comment by Glandos** [comment]
Fixed by #991
